//+------------------------------------------------------------------+
//|                                StraddleScalper_v10.8_GridLadder.mq5|
//|   v10.8 — ไอเดียจากคลิป "Steev GTS EA Gold Trading" (TikTok/IG):    |
//|   วาง BUY STOP หลายชั้น (ladder) เรียงขึ้นเหนือราคา + SELL STOP     |
//|   หลายชั้นเรียงลงใต้ราคา ทุกๆ N points แต่ละไม้ lot เล็ก แทนการวาง  |
//|   straddle เดิมที่มีแค่ 1 คู่ (Buy Stop + Sell Stop) — เป้าหมาย:    |
//|   จับ trend ได้หลายไม้ตามทางที่ราคาวิ่งทะลุ กระจาย risk ต่อไม้เล็ก   |
//|   ลง แทนการเดิมพันกับ breakout จุดเดียว                            |
//|   - ไม่มี Stop & Reverse (grid จับ 2 ทิศทางอยู่แล้วในตัว)           |
//|   - คงไว้: ATR distance scaling, Reward:Risk fix, Consolidation     |
//|     filter, ADX filter, Time filter, Spread filter, Risk Guard      |
//|     (Daily Loss % / Max Drawdown %) จาก v10.6/v10.7                |
//|   - เพิ่ม: Portfolio risk cap บังคับจริง (ลดจำนวนชั้นที่วางถ้า     |
//|     worst-case risk เกินเพดาน InpMaxTotalRiskPercent)               |
//|   - เพิ่ม: Basket Take Profit (ปิดทุกไม้ล็อกกำไรเมื่อกำไรลอยรวม    |
//|     ถึงเป้า InpBasketTPPercent ของ balance)                        |
//+------------------------------------------------------------------+
#property copyright "Generated by Claude"
#property version   "10.81"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\OrderInfo.mqh>
CTrade trade; CPositionInfo posInfo; COrderInfo ordInfo;

#define CLR_BG      C'8,12,20'
#define CLR_HDR     C'10,16,28'
#define CLR_SURFACE C'13,17,26'
#define CLR_BORDER  C'28,38,58'
#define CLR_CYAN    C'0,212,255'
#define CLR_GREEN   C'0,255,157'
#define CLR_RED     C'255,69,96'
#define CLR_AMBER   C'255,184,0'
#define CLR_TEXT    C'201,216,239'
#define CLR_DIM     C'90,112,144'
#define CLR_MUTED   C'40,55,80'
#define PFX         "SS10_"

//=================== Inputs =========================================
input group "1. เงินทุน & ขนาด Lot"
input double  InpRiskPercent      = 1.0;    // เสี่ยงต่อไม้ (% ของ balance) — ใช้เมื่อ InpUseAutoLot=true
input bool    InpUseAutoLot       = false;  // grid scalping: ปกติใช้ lot คงที่เล็กๆ ต่อชั้น (true=คำนวณจาก risk%)
input double  InpMinLot           = 0.01;   // lot ขั้นต่ำ (และ lot คงที่ถ้าปิด AutoLot) — ต่อชั้นของ grid
input double  InpMaxLot           = 0.50;   // lot สูงสุดที่ยอมให้เปิดต่อไม้
input bool    InpLotByBalanceStep = false;
input double  InpBalancePerLot    = 1000;

input group "2. Grid Ladder Entry (ไอเดียจากคลิป Steev GTS — หลายชั้น Buy/Sell Stop)"
input int     InpGridLevels       = 6;     // จำนวนชั้น Buy Stop / Sell Stop แต่ละฝั่ง
input int     InpGridStepPoints   = 150;   // ระยะห่างระหว่างชั้น (points) — เริ่มจากชั้นแรกที่ ATR/Fixed distance
input int     InpGridSLPoints     = 250;   // SL ของแต่ละไม้ที่ trigger จาก grid (points)
input int     InpGridMaxFills     = 4;     // จำกัดจำนวนไม้ที่ trigger พร้อมกันสูงสุด (กัน overexposure ตอนวิ่งแรง)
input int     InpPendingExpiryMin = 0;     // อายุ pending ก่อนหมดอายุอัตโนมัติ (นาที, 0=ไม่หมดอายุ)
input bool    InpRecenterPending  = true;  // เลื่อนทั้ง ladder ตามราคาเมื่อห่างเกิน tolerance
input int     InpRecenterTolerance= 60;    // ขยับ ladder เมื่อราคาห่างจากจุดเดิมเกินกี่ points (ของชั้นแรก)

input group "2b. ATR Volatility Breakout Entry (ระยะชั้นแรกของ ladder)"
input bool    InpUseATREntry        = true;
input ENUM_TIMEFRAMES InpATRTimeframe = PERIOD_M5;
input int     InpATRPeriod          = 14;
input double  InpATRStopMultiplier  = 1.2;
input double  InpATRMinMultiplier   = 0.6;
input int     InpATRAvgPeriod       = 20;
input double  InpATRExpansionRatio  = 1.0;

input group "2c. Reward:Risk Fix + Consolidation Filter (ไอเดียจาก GOLD_ORB)"
input bool    InpUseFixedRewardRisk = true;
input double  InpTPRewardRatio      = 2.0;
input bool    InpUseConsolidationFilter = true;
input int     InpConsolidationBars  = 5;
input double  InpConsolidationMaxRangeATR = 1.5;

input group "4. Breakeven & Trailing Stop (ต่อไม้ — ใช้กับทุก position ที่ trigger จาก grid)"
input int     InpBreakevenStart      = 50;
input int     InpBreakevenLock       = 10;
input int     InpTrailingStart       = 80;
input int     InpTrailingDistance    = 80;
input bool    InpUseProgressiveTrail = true;
input double  InpTrailRatio          = 0.6;

input group "5. ตัวกรองช่วงเวลาเทรด (Time Filter)"
input bool    InpUseTimeFilter    = true;
enum ENUM_SESSION
  {
   SESS_CUSTOM, SESS_ASIAN, SESS_LONDON_NY, SESS_OVERLAP, SESS_ALL
  };
input ENUM_SESSION InpSession     = SESS_LONDON_NY;
input int     InpStartHour        = 14;
input int     InpStartMinute      = 0;
input int     InpEndHour          = 4;
input int     InpEndMinute        = 0;
input int     InpServerGMTOffset  = 3;

input group "6. ตัวกรองแนวโน้มตลาด (ADX)"
input bool    InpUseADXFilter         = true;
input ENUM_TIMEFRAMES InpADXTimeframe = PERIOD_M15;
input int     InpADXPeriod            = 14;
input double  InpADXMinLevel          = 25.0;

input group "7. ตัวกรอง Spread"
input int     InpMaxSpread        = 60;

input group "8. Risk Guard (ป้องกันล้างพอร์ต)"
input bool    InpUseRiskGuard        = true;
input double  InpMaxDailyLossPercent = 10.0;
input double  InpMaxDrawdownPercent  = 20.0;
input double  InpMaxTotalRiskPercent = 5.0;   // ⭐ เพดาน risk รวม — บังคับจริง: ลดจำนวนชั้นที่วางถ้าเกินเพดานนี้ (% balance)

input group "8b. Basket Take Profit (ล็อกกำไรเป็นรอบ)"
input bool    InpUseBasketTP      = true;   // ปิดทุกไม้ + ลบ pending ทันทีเมื่อกำไรลอยรวมถึงเป้า
input double  InpBasketTPPercent  = 2.0;    // เป้ากำไรลอยรวม (% ของ balance) ต่อรอบ grid

input group "9. หน้าจอแสดงผล & Dashboard Export"
input int     InpPanelX           = 20;
input int     InpPanelY           = 30;
input bool    InpDashboardExport  = true;
input string  InpDashboardFile    = "straddle_dashboard.json";

input group "10. ตั้งค่าระบบ"
input long    InpMagicNumber      = 769004;
input string  InpComment          = "SS_v10.8_Grid";

//=================== Globals ========================================
double   g_point; int g_digits;
int      g_adxHandle = INVALID_HANDLE;
int      g_atrHandle = INVALID_HANDLE;
const int PW = 290;
datetime g_lastBarTime = 0;
double   g_gridCenterPrice = 0;   // ราคาอ้างอิงตอนวาง ladder ล่าสุด (สำหรับเช็ค recenter)

// --- Risk Guard ---
datetime g_dayStart        = 0;
double   g_dayStartBalance = 0;
double   g_peakEquity      = 0;
bool     g_haltedByGuard   = false;

//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(30);
   g_point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   g_digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   if(g_point <= 0) return INIT_FAILED;
   g_peakEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   MqlDateTime t0; TimeToStruct(TimeCurrent(), t0); t0.hour=0; t0.min=0; t0.sec=0;
   g_dayStart        = StructToTime(t0);
   g_dayStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   if(InpUseADXFilter)
     {
      g_adxHandle = iADX(_Symbol, InpADXTimeframe, InpADXPeriod);
      if(g_adxHandle == INVALID_HANDLE){ Print("iADX สร้าง handle ไม่สำเร็จ"); return INIT_FAILED; }
     }
   if(InpUseATREntry)
     {
      g_atrHandle = iATR(_Symbol, InpATRTimeframe, InpATRPeriod);
      if(g_atrHandle == INVALID_HANDLE){ Print("iATR สร้าง handle ไม่สำเร็จ"); return INIT_FAILED; }
     }
   PanelCreate();
   EventSetTimer(1);
   Print("SS v10.8 Grid Ladder (", InpGridLevels, " ชั้น/ฝั่ง) เริ่มทำงาน");
   return INIT_SUCCEEDED;
  }

void OnDeinit(const int r)
  {
   EventKillTimer(); PanelDelete();
   if(g_adxHandle!=INVALID_HANDLE) IndicatorRelease(g_adxHandle);
   if(g_atrHandle!=INVALID_HANDLE) IndicatorRelease(g_atrHandle);
  }

bool IsTrendStrongEnough()
  {
   if(!InpUseADXFilter) return true;
   double buf[];
   if(CopyBuffer(g_adxHandle, 0, 1, 1, buf) <= 0) return true;
   return buf[0] >= InpADXMinLevel;
  }

double GetCurrentATR()
  {
   if(g_atrHandle==INVALID_HANDLE) return 0;
   double buf[];
   if(CopyBuffer(g_atrHandle, 0, 1, 1, buf) <= 0) return 0;
   return buf[0];
  }

bool IsVolatilityExpanding()
  {
   if(!InpUseATREntry) return true;
   if(g_atrHandle==INVALID_HANDLE) return true;
   double buf[];
   int n = MathMax(InpATRAvgPeriod,1);
   if(CopyBuffer(g_atrHandle, 0, 1, n, buf) <= 0) return true;
   double sum=0; for(int i=0;i<n;i++) sum+=buf[i];
   double avgATR = sum/n;
   double curATR = buf[n-1];
   if(avgATR<=0) return true;
   return curATR >= avgATR * InpATRExpansionRatio;
  }

//+------------------------------------------------------------------+
//| ระยะของ "ชั้นแรก" ของ ladder (points) — ATR-based หรือคงที่       |
//+------------------------------------------------------------------+
int GetFirstLevelDistancePoints()
  {
   if(!InpUseATREntry) return InpGridStepPoints;
   double atr = GetCurrentATR();
   if(atr<=0) return InpGridStepPoints;
   int dist = (int)MathRound(atr/g_point * InpATRStopMultiplier);
   int minDist = (int)MathRound(InpGridStepPoints * InpATRMinMultiplier);
   return MathMax(dist, minDist);
  }

bool IsConsolidating()
  {
   if(!InpUseConsolidationFilter) return true;
   int n = MathMax(InpConsolidationBars,1);
   double hi = iHigh(_Symbol, PERIOD_M1, 1);
   double lo = iLow(_Symbol, PERIOD_M1, 1);
   for(int i=2;i<=n;i++)
     {
      double h=iHigh(_Symbol,PERIOD_M1,i), l=iLow(_Symbol,PERIOD_M1,i);
      if(h>hi) hi=h;
      if(l<lo) lo=l;
     }
   double range = hi-lo;
   double atr = GetCurrentATR();
   if(atr<=0) return true;
   return range <= atr*InpConsolidationMaxRangeATR;
  }

void OnTimer(){ PanelUpdate(); if(InpDashboardExport) WriteDashboardJSON(); }

//+------------------------------------------------------------------+
void OnTick()
  {
   if(CheckRiskGuard()) return;
   if(CheckBasketTP()) return;

   // ===== จัดการไม้ที่ trigger จาก grid แล้ว (breakeven/trailing ต่อไม้) =====
   ManageGridPositions();

   int myPos  = CountMyPositions();
   int myPend = CountMyPendings();

   // เกินจำนวนไม้ trigger พร้อมกันสูงสุด → ลบ pending ที่เหลือทิ้งชั่วคราว กันเปิดเพิ่ม
   if(myPos >= InpGridMaxFills)
     {
      if(myPend>0) DeleteAllMyPendings();
      return;
     }

   datetime curBar = iTime(_Symbol, PERIOD_M1, 0);
   bool newBar = (curBar != g_lastBarTime);

   if(myPend > 0)
     {
      // ladder ยังอยู่ → re-center ตามราคาเมื่อขึ้นแท่งใหม่ (กันค้างไกลเกินไป)
      if(newBar && InpRecenterPending && IsSpreadOK())
         RecenterGrid();
      g_lastBarTime = curBar;
      return;
     }

   // ไม่มี pending เหลือเลย (ทุกชั้นถูกใช้ไปแล้ว หรือยังไม่เคยวาง) → ตั้ง ladder ใหม่
   if(InpUseTimeFilter && !IsWithinTradingTime()){ g_lastBarTime = curBar; return; }
   if(!IsSpreadOK()){ g_lastBarTime = curBar; return; }
   if(!IsTrendStrongEnough()){ g_lastBarTime = curBar; return; }
   if(!IsVolatilityExpanding()){ g_lastBarTime = curBar; return; }
   if(!IsConsolidating()){ g_lastBarTime = curBar; return; }

   PlaceGridLadder();
   g_lastBarTime = curBar;
  }

//+------------------------------------------------------------------+
bool CheckRiskGuard()
  {
   if(!InpUseRiskGuard) return false;
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   if(equity > g_peakEquity) g_peakEquity = equity;

   MqlDateTime t; TimeToStruct(TimeCurrent(), t); t.hour=0; t.min=0; t.sec=0;
   datetime today = StructToTime(t);
   if(today != g_dayStart)
     {
      g_dayStart        = today;
      g_dayStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
     }

   if(g_haltedByGuard) return true;

   if(InpMaxDrawdownPercent > 0 && g_peakEquity > 0)
     {
      double ddPct = (g_peakEquity - equity) / g_peakEquity * 100.0;
      if(ddPct >= InpMaxDrawdownPercent)
        {
         Print("⛔ Risk Guard: Equity drawdown ", DoubleToString(ddPct,2), "% → ปิดทุกไม้ + หยุด EA ถาวร");
         CloseAllAndFlatten();
         g_haltedByGuard = true;
         return true;
        }
     }

   if(InpMaxDailyLossPercent > 0 && g_dayStartBalance > 0)
     {
      double dayLossPct = (g_dayStartBalance - equity) / g_dayStartBalance * 100.0;
      if(dayLossPct >= InpMaxDailyLossPercent)
        {
         Print("⛔ Risk Guard: ขาดทุนวันนี้ ", DoubleToString(dayLossPct,2), "% → ปิดทุกไม้ + หยุดเทรดจนถึงวันใหม่");
         CloseAllAndFlatten();
         return true;
        }
     }
   return false;
  }

void CloseAllAndFlatten()
  {
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber && posInfo.Symbol()==_Symbol)
            trade.PositionClose(posInfo.Ticket());
   DeleteAllMyPendings();
  }

//+------------------------------------------------------------------+
//| รวมกำไรลอย (floating profit) ของไม้ทั้งหมดของ EA นี้               |
//+------------------------------------------------------------------+
double GetTotalFloatingProfitUSD()
  {
   double total = 0;
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber && posInfo.Symbol()==_Symbol)
            total += posInfo.Profit()+posInfo.Swap();
   return total;
  }

//+------------------------------------------------------------------+
//| Basket TP: ถ้ากำไรลอยรวมของรอบ grid ปัจจุบันถึงเป้า % ของ balance   |
//| ปิดทุกไม้ + ลบ pending ทั้งหมดทันที (ล็อกกำไรเป็นรอบ ไม่ปล่อยให้คืน) |
//+------------------------------------------------------------------+
bool CheckBasketTP()
  {
   if(!InpUseBasketTP || InpBasketTPPercent<=0) return false;
   if(CountMyPositions()<=0) return false;
   double bal = AccountInfoDouble(ACCOUNT_BALANCE);
   if(bal<=0) return false;
   double target = bal * InpBasketTPPercent/100.0;
   double floating = GetTotalFloatingProfitUSD();
   if(floating >= target)
     {
      Print("✅ Basket TP: กำไรลอยรวม $", DoubleToString(floating,2), " ถึงเป้า $", DoubleToString(target,2), " → ปิดทุกไม้ล็อกกำไร");
      CloseAllAndFlatten();
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| คำนวณ risk รวม ($ ที่อาจเสีย) ของไม้ที่เปิดอยู่ทั้งหมดของ EA นี้   |
//+------------------------------------------------------------------+
double GetTotalOpenRiskUSD()
  {
   double total = 0;
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber && posInfo.Symbol()==_Symbol)
           {
            double sl = posInfo.StopLoss();
            if(sl<=0) continue;
            double dist = MathAbs(posInfo.PriceOpen()-sl);
            double tv=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE), ts=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
            if(tv<=0||ts<=0) continue;
            total += (dist/ts)*tv*posInfo.Volume();
           }
   return total;
  }

//+------------------------------------------------------------------+
//| วาง Grid Ladder: BUY STOP × InpGridLevels เหนือราคา                |
//|                   SELL STOP × InpGridLevels ใต้ราคา                |
//| ชั้นที่ i (1..N) ห่างจาก ask/bid = firstDist + (i-1)*StepPoints     |
//+------------------------------------------------------------------+
void PlaceGridLadder()
  {
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   if(ask<=0||bid<=0) return;
   long stopsLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   double minDist = (stopsLevel+2) * g_point;

   int firstDist = GetFirstLevelDistancePoints();
   int tpPts = InpUseFixedRewardRisk ? (int)MathRound(InpGridSLPoints*InpTPRewardRatio) : 0;
   double lot = CalculateLot(InpGridSLPoints);
   if(lot<=0) return;

   datetime exp=0; ENUM_ORDER_TYPE_TIME tt=ORDER_TIME_GTC;
   if(InpPendingExpiryMin>0){exp=TimeCurrent()+InpPendingExpiryMin*60;tt=ORDER_TIME_SPECIFIED;}

   int levels = MathMax(InpGridLevels,1);

   // ===== บังคับ Portfolio Risk Cap จริง: ลดจำนวนชั้นถ้า worst-case (ทุกชั้นทั้ง 2 ฝั่ง trigger) เกินเพดาน =====
   if(InpMaxTotalRiskPercent>0)
     {
      double bal = AccountInfoDouble(ACCOUNT_BALANCE);
      double tv=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE), ts=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
      if(bal>0 && tv>0 && ts>0)
        {
         double riskPerOrder = (InpGridSLPoints*g_point/ts)*tv*lot;
         double budget = bal*InpMaxTotalRiskPercent/100.0 - GetTotalOpenRiskUSD();
         if(riskPerOrder>0)
           {
            int maxLevels = (int)MathFloor(budget/(2.0*riskPerOrder));
            if(maxLevels < levels)
              {
               levels = MathMax(maxLevels,0);
               Print("⚠️ Risk Cap: ลดจำนวนชั้น grid จาก ", InpGridLevels, " เป็น ", levels,
                     " (budget เหลือ $", DoubleToString(budget,2), ", risk/ไม้ $", DoubleToString(riskPerOrder,2), ")");
              }
           }
        }
     }
   if(levels<=0){ Print("⛔ Risk Cap: เต็มเพดาน risk รวมแล้ว — ไม่วาง grid รอบนี้"); return; }
   for(int i=1;i<=levels;i++)
     {
      double distPts = firstDist + (i-1)*InpGridStepPoints;
      double useDist = MathMax(distPts*g_point, minDist);

      double bP = NormalizeDouble(ask+useDist, g_digits);
      double sLPrice = NormalizeDouble(bid-useDist, g_digits);

      double slBuy  = NormalizeDouble(bP - InpGridSLPoints*g_point, g_digits);
      double slSell = NormalizeDouble(sLPrice + InpGridSLPoints*g_point, g_digits);
      double tpBuy  = (tpPts>0) ? NormalizeDouble(bP + tpPts*g_point, g_digits) : 0;
      double tpSell = (tpPts>0) ? NormalizeDouble(sLPrice - tpPts*g_point, g_digits) : 0;

      if(!trade.BuyStop(lot,bP,_Symbol,slBuy,tpBuy,tt,exp,InpComment+"_L"+IntegerToString(i)))
         Print("⚠️ Grid BuyStop ชั้น ", i, " วางไม่สำเร็จ: ", trade.ResultRetcodeDescription());
      if(!trade.SellStop(lot,sLPrice,_Symbol,slSell,tpSell,tt,exp,InpComment+"_L"+IntegerToString(i)))
         Print("⚠️ Grid SellStop ชั้น ", i, " วางไม่สำเร็จ: ", trade.ResultRetcodeDescription());
     }

   g_gridCenterPrice = (ask+bid)/2.0;
   Print("Grid Ladder วางแล้ว: ", levels, " ชั้น/ฝั่ง, firstDist=", firstDist, "pts, step=", InpGridStepPoints, "pts, lot/ชั้น=", lot);
  }

//+------------------------------------------------------------------+
//| Re-center ladder: ถ้าราคาห่างจากจุดที่วางครั้งล่าสุดเกิน tolerance |
//| ลบ pending เดิมทั้งหมด แล้ววางใหม่รอบราคาปัจจุบัน                  |
//+------------------------------------------------------------------+
void RecenterGrid()
  {
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   if(ask<=0||bid<=0) return;
   double mid = (ask+bid)/2.0;
   if(g_gridCenterPrice<=0){ g_gridCenterPrice = mid; return; }

   double driftPts = MathAbs(mid-g_gridCenterPrice)/g_point;
   if(driftPts > InpRecenterTolerance)
     {
      DeleteAllMyPendings();
      PlaceGridLadder();
     }
  }

//+------------------------------------------------------------------+
//| Breakeven + Trailing ต่อไม้ สำหรับทุก position ที่ trigger จาก grid|
//+------------------------------------------------------------------+
double ComputeTrailCandidate(bool isBuy, double open, double bid, double ask, double profitPts)
  {
   if(InpTrailingStart>0 && profitPts>=InpTrailingStart)
      return isBuy ? NormalizeDouble(bid-InpTrailingDistance*g_point,g_digits)
                   : NormalizeDouble(ask+InpTrailingDistance*g_point,g_digits);
   if(InpBreakevenStart>0 && profitPts>=InpBreakevenStart)
     {
      if(InpUseProgressiveTrail)
        {
         double excess = profitPts - InpBreakevenStart;
         double extra  = excess*InpTrailRatio*g_point;
         return isBuy ? NormalizeDouble(open+InpBreakevenLock*g_point+extra,g_digits)
                      : NormalizeDouble(open-InpBreakevenLock*g_point-extra,g_digits);
        }
      return isBuy ? NormalizeDouble(open+InpBreakevenLock*g_point,g_digits)
                   : NormalizeDouble(open-InpBreakevenLock*g_point,g_digits);
     }
   return 0;
  }

void ManageGridPositions()
  {
   double bid=SymbolInfoDouble(_Symbol,SYMBOL_BID), ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK);
   for(int i=PositionsTotal()-1;i>=0;i--)
     {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic()!=InpMagicNumber || posInfo.Symbol()!=_Symbol) continue;

      double open=posInfo.PriceOpen(), sl=posInfo.StopLoss(), tp=posInfo.TakeProfit();
      ulong tkt=posInfo.Ticket();
      bool isBuy = (posInfo.PositionType()==POSITION_TYPE_BUY);
      double profitPts = isBuy ? (bid-open)/g_point : (open-ask)/g_point;

      double cand = ComputeTrailCandidate(isBuy, open, bid, ask, profitPts);
      if(cand<=0) continue;

      if(isBuy)
        {
         if(cand>sl+g_point*0.5 && cand<bid) trade.PositionModify(tkt,cand,tp);
        }
      else
        {
         if((sl==0||cand<sl-g_point*0.5) && cand>ask) trade.PositionModify(tkt,cand,tp);
        }
     }
  }

//=================== PANEL ==========================================
void PanelCreate()
  {
   int x=InpPanelX, y=InpPanelY;
   Rect(PFX+"BG", x, y, PW, 300, CLR_BG, CLR_BORDER);
   Rect(PFX+"ACC", x, y, PW, 2, CLR_CYAN, CLR_CYAN);
   Rect(PFX+"HDR", x, y+2, PW, 46, CLR_HDR, CLR_BG);
   Label(PFX+"T1", x+12, y+9, "◈  GRID LADDER SCALPER", "Consolas", 10, CLR_CYAN);
   Label(PFX+"T2", x+PW-95, y+9, "v10.8·Grid", "Consolas", 9, CLR_AMBER);
   Label(PFX+"T3", x+12, y+28, _Symbol+" · M1 · Multi-Level Ladder", "Consolas", 8, CLR_DIM);
   Rect(PFX+"D1", x, y+48, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"STBG", x, y+49, PW, 26, CLR_SURFACE, CLR_BG);
   Rect(PFX+"DOT", x+12, y+58, 8, 8, CLR_GREEN, CLR_GREEN);
   Label(PFX+"STAT", x+26, y+56, "READY", "Consolas", 9, CLR_GREEN);
   Label(PFX+"TIME", x+150, y+56, "ไทย: --", "Consolas", 8, CLR_DIM);
   Rect(PFX+"D2", x, y+76, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"ACB", x, y+77, PW, 70, CLR_BG, CLR_BG);
   int ay=y+82;
   Label(PFX+"BL", x+12, ay, "BALANCE", "Consolas", 8, CLR_DIM);
   Label(PFX+"BV", x+90, ay, "$0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"EQ", x+12, ay+22, "EQUITY", "Consolas", 8, CLR_DIM);
   Label(PFX+"EV", x+90, ay+22, "$0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"FL", x+190, ay+22, "+$0", "Consolas", 8, CLR_GREEN);
   Label(PFX+"TD", x+12, ay+44, "TODAY", "Consolas", 8, CLR_DIM);
   Label(PFX+"TV", x+90, ay+44, "+$0", "Consolas", 9, CLR_GREEN);
   Rect(PFX+"D3", x, y+147, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"PRB", x, y+148, PW, 46, CLR_SURFACE, CLR_BG);
   int py=y+153;
   Label(PFX+"DIR", x+12, py, "FILLS", "Consolas", 8, CLR_DIM);
   Label(PFX+"DIRV", x+60, py, "0", "Consolas", 9, CLR_CYAN);
   Label(PFX+"RV", x+110, py, "MAXFILL", "Consolas", 8, CLR_DIM);
   Label(PFX+"RVV", x+185, py, "0", "Consolas", 9, CLR_AMBER);
   Label(PFX+"LT", x+12, py+22, "LOT/ชั้น", "Consolas", 8, CLR_DIM);
   Label(PFX+"LTV", x+70, py+22, "0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"GP", x+130, py+22, "RISK$", "Consolas", 8, CLR_DIM);
   Label(PFX+"GPV", x+185, py+22, "0", "Consolas", 9, CLR_RED);
   Rect(PFX+"D4", x, y+195, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"SSB", x, y+196, PW, 46, CLR_BG, CLR_BG);
   int sy=y+201;
   Label(PFX+"WN", x+12, sy, "WIN", "Consolas", 8, CLR_DIM);
   Label(PFX+"WNV", x+42, sy, "0", "Consolas", 9, CLR_GREEN);
   Label(PFX+"LS", x+78, sy, "LOSS", "Consolas", 8, CLR_DIM);
   Label(PFX+"LSV", x+112, sy, "0", "Consolas", 9, CLR_RED);
   Label(PFX+"WR", x+148, sy, "WR", "Consolas", 8, CLR_DIM);
   Label(PFX+"WRV", x+172, sy, "0%", "Consolas", 9, CLR_CYAN);
   Label(PFX+"PF", x+12, sy+22, "PF", "Consolas", 8, CLR_DIM);
   Label(PFX+"PFV", x+38, sy+22, "0", "Consolas", 9, CLR_AMBER);
   Label(PFX+"SP", x+138, sy+22, "SPREAD", "Consolas", 8, CLR_DIM);
   Label(PFX+"SPV", x+205, sy+22, "0", "Consolas", 9, CLR_TEXT);
   Rect(PFX+"D5", x, y+242, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"BEB", x, y+243, PW, 30, CLR_SURFACE, CLR_BG);
   int by=y+253;
   Label(PFX+"NEEDL", x+12, by, "TOTAL RISK", "Consolas", 8, CLR_DIM);
   Label(PFX+"NEEDV", x+90, by, "--", "Consolas", 9, CLR_TEXT);
   Label(PFX+"BUFL", x+150, by, "CAP%", "Consolas", 8, CLR_DIM);
   Label(PFX+"BUFV", x+195, by, "--", "Consolas", 9, CLR_DIM);
   Rect(PFX+"BOT", x, y+274, PW, 18, CLR_HDR, CLR_BG);
   Label(PFX+"BX", x+12, y+279, "MAGIC: "+IntegerToString(InpMagicNumber), "Consolas", 7, CLR_MUTED);
   ChartRedraw(0);
  }

void PanelUpdate()
  {
   double bal=AccountInfoDouble(ACCOUNT_BALANCE),eq=AccountInfoDouble(ACCOUNT_EQUITY),fl=eq-bal;
   long spread=SymbolInfoInteger(_Symbol,SYMBOL_SPREAD);
   double lot=CalculateLot(InpGridSLPoints);
   MqlDateTime t; TimeToStruct(TimeCurrent(),t); t.hour=0;t.min=0;t.sec=0;
   datetime today=StructToTime(t);
   HistorySelect(today,TimeCurrent());
   double dP=0,dL=0; int w=0,l=0;
   for(int i=0;i<HistoryDealsTotal();i++)
     {
      ulong tk=HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(tk,DEAL_MAGIC)!=InpMagicNumber) continue;
      if(HistoryDealGetInteger(tk,DEAL_ENTRY)!=DEAL_ENTRY_OUT) continue;
      double p=HistoryDealGetDouble(tk,DEAL_PROFIT)+HistoryDealGetDouble(tk,DEAL_SWAP)+HistoryDealGetDouble(tk,DEAL_COMMISSION);
      if(p>=0){dP+=p;w++;}else{dL+=MathAbs(p);l++;}
     }
   double net=dP-dL,pf=(dL>0?dP/dL:(dP>0?999:0)),wr=(w+l>0?100.0*w/(w+l):0);

   string stat="READY"; color dc=CLR_GREEN,sc=CLR_GREEN;
   bool timeOk = !InpUseTimeFilter || IsWithinTradingTime();
   int nPos = CountMyPositions();
   if(nPos>0){stat="GRID FILLED x"+IntegerToString(nPos);dc=CLR_CYAN;sc=CLR_CYAN;}
   else if(CountMyPendings()>0){stat="LADDER ARMED";dc=CLR_AMBER;sc=CLR_AMBER;}
   else if(!timeOk){stat="OUT OF TIME";dc=CLR_RED;sc=CLR_RED;}
   ObjColor(PFX+"DOT",dc); ObjColor(PFX+"STAT",sc); ObjText(PFX+"STAT",stat);
   datetime thaiTime=TimeCurrent()-InpServerGMTOffset*3600+7*3600;
   MqlDateTime tn; TimeToStruct(thaiTime,tn);
   ObjText(PFX+"TIME",StringFormat("ไทย: %02d:%02d %s",tn.hour,tn.min,timeOk?"✓":"✗"));
   ObjColor(PFX+"TIME",timeOk?CLR_DIM:CLR_RED);
   ObjText(PFX+"BV","$"+DoubleToString(bal,2));
   ObjText(PFX+"EV","$"+DoubleToString(eq,2));
   ObjText(PFX+"FL",(fl>=0?"+":"")+DoubleToString(fl,2)); ObjColor(PFX+"FL",fl>=0?CLR_GREEN:CLR_RED);
   ObjText(PFX+"TV",(net>=0?"+$":"-$")+DoubleToString(MathAbs(net),2)); ObjColor(PFX+"TV",net>=0?CLR_GREEN:CLR_RED);
   ObjText(PFX+"DIRV",(string)nPos);
   ObjText(PFX+"RVV",(string)InpGridMaxFills);
   ObjText(PFX+"LTV",DoubleToString(lot,2));
   double totalRisk = GetTotalOpenRiskUSD();
   ObjText(PFX+"GPV","$"+DoubleToString(totalRisk,2));
   ObjColor(PFX+"GPV", totalRisk >= bal*InpMaxTotalRiskPercent/100.0*0.9 ? CLR_RED : CLR_TEXT);
   ObjText(PFX+"WNV",(string)w);
   ObjText(PFX+"LSV",(string)l);
   ObjText(PFX+"WRV",DoubleToString(wr,1)+"%");
   ObjText(PFX+"PFV",pf>=999?"inf":DoubleToString(pf,2));
   ObjText(PFX+"NEEDV","$"+DoubleToString(totalRisk,2));
   ObjText(PFX+"BUFV",DoubleToString(InpMaxTotalRiskPercent,1)+"%");
   ObjColor(PFX+"BUFV",CLR_DIM);
   ObjText(PFX+"SPV",(string)spread);
   ObjColor(PFX+"SPV",(InpMaxSpread<=0||spread<=InpMaxSpread)?CLR_GREEN:CLR_RED);
   ChartRedraw(0);
  }

void PanelDelete(){ ObjectsDeleteAll(0,PFX); ChartRedraw(0); }
void Rect(string n,int x,int y,int w,int h,color bg,color bd)
  {
   if(ObjectFind(0,n)<0) ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);
   ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);
   ObjectSetInteger(0,n,OBJPROP_XSIZE,w); ObjectSetInteger(0,n,OBJPROP_YSIZE,h);
   ObjectSetInteger(0,n,OBJPROP_BGCOLOR,bg); ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,bd);
   ObjectSetInteger(0,n,OBJPROP_BORDER_TYPE,BORDER_FLAT); ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);
   ObjectSetInteger(0,n,OBJPROP_BACK,false); ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,n,OBJPROP_HIDDEN,true);
  }
void Label(string n,int x,int y,string txt,string f,int s,color c)
  {
   if(ObjectFind(0,n)<0) ObjectCreate(0,n,OBJ_LABEL,0,0,0);
   ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);
   ObjectSetString(0,n,OBJPROP_TEXT,txt); ObjectSetString(0,n,OBJPROP_FONT,f);
   ObjectSetInteger(0,n,OBJPROP_FONTSIZE,s); ObjectSetInteger(0,n,OBJPROP_COLOR,c);
   ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);
   ObjectSetInteger(0,n,OBJPROP_BACK,false); ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,n,OBJPROP_HIDDEN,true);
  }
void ObjText(string n,string t){ ObjectSetString(0,n,OBJPROP_TEXT,t); }
void ObjColor(string n,color c){ ObjectSetInteger(0,n,OBJPROP_COLOR,c); }

void WriteDashboardJSON()
  {
   double bal=AccountInfoDouble(ACCOUNT_BALANCE),eq=AccountInfoDouble(ACCOUNT_EQUITY);
   long sp=SymbolInfoInteger(_Symbol,SYMBOL_SPREAD);
   bool timeOk = !InpUseTimeFilter || IsWithinTradingTime();
   string as=!timeOk?"low":"active";
   MqlDateTime t; TimeToStruct(TimeCurrent(),t); t.hour=0;t.min=0;t.sec=0;
   datetime today=StructToTime(t);
   HistorySelect(today,TimeCurrent());
   double dP=0,dL=0,gW=0,gL=0; int w=0,l=0; string dj=""; int sh=0;
   for(int i=HistoryDealsTotal()-1;i>=0;i--)
     {
      ulong tk=HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(tk,DEAL_MAGIC)!=InpMagicNumber) continue;
      if(HistoryDealGetInteger(tk,DEAL_ENTRY)!=DEAL_ENTRY_OUT) continue;
      double p=HistoryDealGetDouble(tk,DEAL_PROFIT)+HistoryDealGetDouble(tk,DEAL_SWAP)+HistoryDealGetDouble(tk,DEAL_COMMISSION);
      if(p>=0){dP+=p;gW+=p;w++;}else{dL+=MathAbs(p);gL+=MathAbs(p);l++;}
      if(sh<12){
        double vol=HistoryDealGetDouble(tk,DEAL_VOLUME); datetime dt=(datetime)HistoryDealGetInteger(tk,DEAL_TIME);
        long dt2=HistoryDealGetInteger(tk,DEAL_TYPE);
        if(sh>0) dj+=",";
        dj+=StringFormat("{\"time\":\"%s\",\"type\":\"%s\",\"lots\":%.2f,\"profit\":%.2f}",TimeToString(dt,TIME_MINUTES),dt2==DEAL_TYPE_BUY?"SELL":"BUY",vol,p); sh++;}
     }
   double pf=(gL>0?gW/gL:(gW>0?999:0)),wr=(w+l>0?100.0*w/(w+l):0);
   string pj=""; int np=0;
   for(int i=0;i<PositionsTotal();i++){
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic()!=InpMagicNumber||posInfo.Symbol()!=_Symbol) continue;
      if(np>0) pj+=",";
      pj+=StringFormat("{\"ticket\":%llu,\"type\":\"%s\",\"lots\":%.2f,\"open\":%.2f,\"current\":%.2f,\"profit\":%.2f}",
         posInfo.Ticket(),posInfo.PositionType()==POSITION_TYPE_BUY?"BUY":"SELL",posInfo.Volume(),posInfo.PriceOpen(),posInfo.PriceCurrent(),posInfo.Profit()); np++;}
   string json="{";
   json+=StringFormat("\"updated\":\"%s\",\"symbol\":\"%s\",",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS),_Symbol);
   json+=StringFormat("\"balance\":%.2f,\"equity\":%.2f,\"floating\":%.2f,",bal,eq,eq-bal);
   json+=StringFormat("\"dailyProfit\":%.2f,\"dailyLoss\":%.2f,",dP,dL);
   json+=StringFormat("\"wins\":%d,\"losses\":%d,\"winrate\":%.1f,\"profitFactor\":%.2f,",w,l,wr,pf);
   json+=StringFormat("\"gridLevels\":%d,\"gridStepPts\":%d,\"gridSLPts\":%d,",InpGridLevels,InpGridStepPoints,InpGridSLPoints);
   json+=StringFormat("\"totalOpenRiskUSD\":%.2f,\"maxTotalRiskPct\":%.2f,",GetTotalOpenRiskUSD(),InpMaxTotalRiskPercent);
   json+=StringFormat("\"spread\":%d,\"lot\":%.2f,\"pendings\":%d,\"fills\":%d,",sp,CalculateLot(InpGridSLPoints),CountMyPendings(),CountMyPositions());
   json+="\"positions\":["+pj+"],\"deals\":["+dj+"]}";
   int fh=FileOpen(InpDashboardFile,FILE_WRITE|FILE_TXT|FILE_ANSI);
   if(fh!=INVALID_HANDLE){FileWriteString(fh,json);FileClose(fh);}
  }

double CalculateLot(int slP)
  {
   double lot;
   if(!InpUseAutoLot) lot=InpMinLot;
   else if(InpLotByBalanceStep) lot=MathFloor(AccountInfoDouble(ACCOUNT_BALANCE)/InpBalancePerLot)*0.01;
   else{
      double bal=AccountInfoDouble(ACCOUNT_BALANCE),risk=bal*InpRiskPercent/100.0;
      double tv=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE),ts=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
      if(tv<=0||ts<=0) return InpMinLot;
      double lpl=(slP*g_point/ts)*tv; if(lpl<=0) return InpMinLot;
      lot=risk/lpl;}
   double vMin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),vMax=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),vS=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lot=MathMax(lot,MathMax(InpMinLot,vMin)); lot=MathMin(lot,MathMin(InpMaxLot,vMax));
   if(vS>0) lot=MathFloor(lot/vS)*vS;
   return NormalizeDouble(lot,2);
  }

int CountMyPositions(){int n=0;for(int i=PositionsTotal()-1;i>=0;i--) if(posInfo.SelectByIndex(i)) if(posInfo.Magic()==InpMagicNumber&&posInfo.Symbol()==_Symbol) n++;return n;}
int CountMyPendings(){int n=0;for(int i=OrdersTotal()-1;i>=0;i--) if(ordInfo.SelectByIndex(i)) if(ordInfo.Magic()==InpMagicNumber&&ordInfo.Symbol()==_Symbol) n++;return n;}
void DeleteAllMyPendings(){for(int i=OrdersTotal()-1;i>=0;i--) if(ordInfo.SelectByIndex(i)) if(ordInfo.Magic()==InpMagicNumber&&ordInfo.Symbol()==_Symbol) trade.OrderDelete(ordInfo.Ticket());}

bool IsWithinTradingTime()
  {
   datetime thaiNow=TimeCurrent()-InpServerGMTOffset*3600+7*3600;
   MqlDateTime t; TimeToStruct(thaiNow,t);
   int cur=t.hour*60+t.min, s, e;
   switch(InpSession)
     {
      case SESS_ASIAN:     s=6*60;  e=14*60; break;
      case SESS_LONDON_NY: s=14*60; e=4*60;  break;
      case SESS_OVERLAP:   s=19*60; e=23*60; break;
      case SESS_ALL:       return true;
      default:             s=InpStartHour*60+InpStartMinute; e=InpEndHour*60+InpEndMinute; break;
     }
   return(s<=e ? cur>=s&&cur<=e : cur>=s||cur<=e);
  }
bool IsSpreadOK(){if(InpMaxSpread<=0) return true; return SymbolInfoInteger(_Symbol,SYMBOL_SPREAD)<=InpMaxSpread;}
