//+------------------------------------------------------------------+
//|                                            StraddleScalper_v10.4.mq5|
//|   v10.5 — ปรับโครงสร้างใหม่: ตัด Zone Bounce (ปิดอยู่/ไม่ใช้) ออก   |
//|   จัดกลุ่ม input ใหม่ให้อ่านง่าย ลดความสับสนเวลาตั้งค่า            |
//|   กลไกหลัก:                                                      |
//|   • วาง Buy Stop + Sell Stop รอ breakout (Straddle)               |
//|   • position รัน → trailing SL เลื่อนตาม                          |
//|   • Reverse Stop (pending ฝั่งตรงข้าม) เกาะติด SL ห่าง gap นิดนึง  |
//|   • ราคาเด้งแตะ SL → ปิดไม้เดิม + pending trigger เปิดสวนทันที    |
//|   • ไม้ใหม่กันหน้าทุนเร็ว + วาง reverse stop ตามต่อ              |
//|   • ตัวกรอง: Time Filter (เวลาไทย) + ADX (กันตลาด sideway) + Spread |
//|   • Risk Guard ป้องกันล้างพอร์ต + HUD Panel + Dashboard export    |
//+------------------------------------------------------------------+
#property copyright "Generated by Claude"
#property version   "10.50"

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\OrderInfo.mqh>
CTrade trade; CPositionInfo posInfo; COrderInfo ordInfo;

#define CLR_BG      C'8,12,20'
#define CLR_HDR     C'10,16,28'
#define CLR_SURFACE C'13,17,26'
#define CLR_BORDER  C'28,38,58'
#define CLR_CYAN    C'0,212,255'
#define CLR_GREEN   C'0,255,157'
#define CLR_RED     C'255,69,96'
#define CLR_AMBER   C'255,184,0'
#define CLR_TEXT    C'201,216,239'
#define CLR_DIM     C'90,112,144'
#define CLR_MUTED   C'40,55,80'
#define PFX         "SS10_"

//=================== Inputs =========================================
input group "1. เงินทุน & ขนาด Lot"
input double  InpRiskPercent      = 1.0;    // เสี่ยงต่อไม้ (% ของ balance) — ใช้เมื่อ InpUseAutoLot=true
input bool    InpUseAutoLot       = true;   // true = คำนวณ lot จาก RiskPercent, false = ใช้ InpMinLot คงที่
input double  InpMinLot           = 0.01;   // lot ขั้นต่ำ (และ lot คงที่ถ้าปิด AutoLot)
input double  InpMaxLot           = 0.50;   // lot สูงสุดที่ยอมให้เปิด
input bool    InpLotByBalanceStep = false;  // true = lot ตามขั้น balance แทนการคำนวณจาก risk%
input double  InpBalancePerLot    = 1000;   // balance ทุกกี่ $ เพิ่ม lot 0.01 (ใช้เมื่อ LotByBalanceStep=true)

input group "2. วาง Straddle เริ่มต้น (Buy Stop + Sell Stop รอ breakout)"
input int     InpStopDistance     = 220;   // ระยะห่างจากราคาปัจจุบัน ที่จะวาง Buy/Sell Stop (points)
input int     InpPendingExpiryMin = 30;    // อายุ pending ก่อนหมดอายุอัตโนมัติ (นาที, 0=ไม่หมดอายุ)
input bool    InpRecenterPending  = true;  // เลื่อน straddle ตามราคาทุกแท่งใหม่ (กัน pending ค้างไกลเกิน)
input int     InpRecenterTolerance= 20;    // ขยับ pending เมื่อราคาห่างจากจุดเดิมเกินกี่ points

input group "3. Stop & Reverse (กลับไม้สวนอัตโนมัติเมื่อโดน Stop)"
input bool    InpUseReverse         = true;  // เปิด/ปิด ระบบเปิดไม้สวนอัตโนมัติ
input int     InpInitialSL          = 200;   // Stop Loss เริ่มต้นของไม้ที่เพิ่งเปิด (points)
input int     InpTakeProfit         = 0;     // Take Profit ของไม้ (points, 0=ปิด → ใช้ Trailing+Reverse คุมกำไรแทน)
input int     InpReverseGap         = 50;    // ระยะห่างระหว่าง SL กับจุดวาง Reverse Stop (points)
input int     InpMaxReverses        = 4;     // จำกัดจำนวนครั้งที่กลับไม้สวนได้ต่อรอบ (กันวน whipsaw ไม่หยุด)
input int     InpReverseCooldownM   = 5;     // พักเทรดหลังกลับไม้ครบจำนวนสูงสุด (นาที, 0=ไม่พัก)
input int     InpReverseTimeoutBars = 3;     // ถ้า Reverse Stop ค้างไม่ trigger เกินกี่แท่ง → ยกเลิกแล้ววาง straddle ใหม่ (0=ปิด)
input int     InpMaxPendingDistance = 250;   // ถ้า pending ห่างราคาปัจจุบันเกินกี่ points → ถือว่าหนีไกล วางใหม่ทันที

input group "4. Breakeven & Trailing Stop (กันทุน + ล็อกกำไร)"
input int     InpBreakevenStart      = 50;    // กำไรถึงกี่ points → เริ่มเลื่อน SL มากันทุน
input int     InpBreakevenLock       = 10;    // ล็อกกำไรไว้กี่ points ตอนกันทุน
input int     InpTrailingStart       = 80;    // กำไรถึงกี่ points → เริ่ม Trailing SL ตามราคา
input int     InpTrailingDistance    = 80;    // ระยะห่างของ Trailing SL จากราคา (points)
input bool    InpUseProgressiveTrail = true;  // true = SL ไหลขยับต่อเนื่องระหว่าง Breakeven→TrailingStart (ไม่ค้างนิ่ง)
input double  InpTrailRatio          = 0.6;   // อัตราขยับ SL ต่อกำไรส่วนเกิน ในโหมด Progressive (0-1)

input group "5. ตัวกรองช่วงเวลาเทรด (Time Filter)"
input bool    InpUseTimeFilter    = true;   // เปิด/ปิด การจำกัดช่วงเวลาเทรด
enum ENUM_SESSION
  {
   SESS_CUSTOM,        // กำหนดเอง (ใช้ StartHour/EndHour ด้านล่าง)
   SESS_ASIAN,         // Asian (06:00-14:00 ไทย)
   SESS_LONDON_NY,     // London+NY (14:00-04:00 ไทย) — ทองมักมี trend ช่วงนี้
   SESS_OVERLAP,       // Overlap London/NY (19:00-23:00 ไทย)
   SESS_ALL            // เทรดได้ทั้งวัน (ไม่กรอง)
  };
input ENUM_SESSION InpSession     = SESS_LONDON_NY;  // เลือกช่วงเวลาที่อนุญาตให้เปิดไม้ใหม่
input int     InpStartHour        = 14;   // ใช้เมื่อ InpSession = SESS_CUSTOM
input int     InpStartMinute      = 0;
input int     InpEndHour          = 4;
input int     InpEndMinute        = 0;
input int     InpServerGMTOffset  = 3;    // ส่วนต่างเวลา server กับ GMT (ใช้แปลงเป็นเวลาไทย)

input group "6. ตัวกรองแนวโน้มตลาด (ADX) — กันวาง Straddle ตอนตลาด sideway"
input bool    InpUseADXFilter         = true;          // เปิด/ปิด ตัวกรอง ADX
input ENUM_TIMEFRAMES InpADXTimeframe = PERIOD_M15;     // timeframe ที่ใช้วัด ADX (สูงกว่า M1 ที่เทรดจริง กันสัญญาณสั่น)
input int     InpADXPeriod            = 14;
input double  InpADXMinLevel          = 25.0;           // ADX ต้อง ≥ ค่านี้ถึงเปิดไม้ใหม่ได้ (ต่ำกว่า = ตลาด sideway)

input group "7. ตัวกรอง Spread"
input int     InpMaxSpread        = 60;   // spread เกินกี่ points → งดเปิดไม้ใหม่ชั่วคราว

input group "8. Risk Guard (ป้องกันล้างพอร์ต)"
input bool    InpUseRiskGuard        = true;   // เปิด/ปิด ระบบป้องกันล้างพอร์ต
input double  InpMaxDailyLossPercent = 10.0;   // ขาดทุนสะสมของวันเกิน % นี้ของ balance ต้นวัน → หยุดเทรดจนถึงวันใหม่
input double  InpMaxDrawdownPercent  = 20.0;   // equity ร่วงจาก peak เกิน % นี้ → ปิดทุกไม้ + หยุด EA ถาวร (ต้องรีสตาร์ทเอง)

input group "9. หน้าจอแสดงผล & Dashboard Export"
input int     InpPanelX           = 20;
input int     InpPanelY           = 30;
input bool    InpDashboardExport  = true;
input string  InpDashboardFile    = "straddle_dashboard.json";

input group "10. ตั้งค่าระบบ"
input long    InpMagicNumber      = 769001;   // เลขประจำตัว EA (แยกไม้ของ EA นี้จากไม้อื่น)
input string  InpComment          = "SS_v10.5";

//=================== Globals ========================================
double   g_point; int g_digits;
int      g_adxHandle = INVALID_HANDLE;
const int PW = 290;
int      g_reverseCount = 0;
datetime g_cooldownUntil = 0;
int      g_lastDir = 0;            // 1=BUY, -1=SELL, 0=none
ulong    g_revStopTicket = 0;      // ticket ของ reverse stop ที่กำลังเกาะ SL
datetime g_lastBarTime = 0;        // เวลาแท่งล่าสุด (สำหรับ re-center)
datetime g_singlePendBarTime = 0;  // เวลาแท่งที่เริ่มเหลือ pending ฝั่งเดียว (timeout ใหม่)

// --- Risk Guard ---
datetime g_dayStart        = 0;      // เวลาเที่ยงคืนของวันปัจจุบัน (server time)
double   g_dayStartBalance = 0;      // balance ตอนต้นวัน (สำหรับคำนวณ daily loss %)
double   g_peakEquity      = 0;      // equity สูงสุดที่เคยทำได้ (สำหรับคำนวณ drawdown % จาก peak)
bool     g_haltedByGuard   = false;  // true = Risk Guard สั่งหยุดเทรดถาวร (max drawdown ชน)

//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(30);
   g_point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   g_digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   if(g_point <= 0) return INIT_FAILED;
   g_peakEquity = AccountInfoDouble(ACCOUNT_EQUITY);
   MqlDateTime t0; TimeToStruct(TimeCurrent(), t0); t0.hour=0; t0.min=0; t0.sec=0;
   g_dayStart        = StructToTime(t0);
   g_dayStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
   if(InpUseADXFilter)
     {
      g_adxHandle = iADX(_Symbol, InpADXTimeframe, InpADXPeriod);
      if(g_adxHandle == INVALID_HANDLE){ Print("iADX สร้าง handle ไม่สำเร็จ"); return INIT_FAILED; }
     }
   PanelCreate();
   EventSetTimer(1);
   Print("SS v10.5 (Straddle + Reverse + Risk Guard + ADX/Time Filter + Progressive Trail) เริ่มทำงาน");
   return INIT_SUCCEEDED;
  }

void OnDeinit(const int r){ EventKillTimer(); PanelDelete(); if(g_adxHandle!=INVALID_HANDLE) IndicatorRelease(g_adxHandle); }

bool IsTrendStrongEnough()
  {
   if(!InpUseADXFilter) return true;
   double buf[];
   if(CopyBuffer(g_adxHandle, 0, 1, 1, buf) <= 0) return true;  // ข้อมูลไม่พร้อม → ไม่บล็อกการเทรด
   return buf[0] >= InpADXMinLevel;
  }
void OnTimer(){ PanelUpdate(); if(InpDashboardExport) WriteDashboardJSON(); }

//+------------------------------------------------------------------+
void OnTick()
  {
   if(CheckRiskGuard()) return;   // ⭐ หยุดเทรดทันทีถ้าชน daily loss / max drawdown limit

   int myPos  = CountMyPositions();
   int myPend = CountMyPendings();

   // ============================================================
   // STATE A: มี position → trailing + เลื่อน reverse stop เกาะ SL
   // ============================================================
   if(myPos > 0)
     {
      ManagePositionAndReverse();
      return;
     }

   // ============================================================
   // STATE B: ไม่มี position แต่มี pending ค้าง
   // ตรวจจาก "จำนวนฝั่ง" ของ pending จริง (ไม่พึ่ง g_lastDir)
   // ============================================================
   if(myPend >= 1)
     {
      int nBuy=0, nSell=0;
      CountPendingSides(nBuy, nSell);
      bool bothSides = (nBuy>0 && nSell>0);

      // --- B2: straddle เริ่มต้นครบ 2 ฝั่ง (ยังไม่ breakout) → re-center ---
      if(bothSides)
        {
         g_singlePendBarTime = 0;   // reset timer (ยังครบ 2 ฝั่ง)
         if(InpUseTimeFilter && !IsWithinTradingTime()){ DeleteAllMyPendings(); ResetCycle(); return; }
         if(InpRecenterPending && IsSpreadOK()) RecenterStraddle();
         return;
        }

      // --- B1: เหลือ pending ฝั่งเดียว ---
      // ⭐ แยก 2 เคส: "วางครั้งแรกไม่ครบ" (g_lastDir==0, ไม่เคยมี position)
      //              vs "orphan หลัง position ปิด" (g_lastDir!=0)
      if(g_lastDir == 0)
        {
         // ยังไม่เคยมี position เลย = ครั้งแรกวางไม่ครบ (โบรกอาจปฏิเสธฝั่งหนึ่ง)
         // แก้ทันที ไม่รอ timeout — เติมฝั่งที่หายไป
         Print("ตรวจพบ straddle เริ่มต้นไม่ครบ (g_lastDir=0) → เติมฝั่งที่หายไปทันที");
         PlaceInitialStraddle();
         return;
        }

      // เคยมี position มาก่อน = นี่คือ orphan reverse stop ที่รอ trigger
      // กันค้าง #1: ราคาวิ่งหนีไกลเกิน → ทิ้งวาง straddle ใหม่
      if(SinglePendingTooFar())
        {
         DeleteAllMyPendings(); ResetCycle();
         // ตกไปวาง straddle ใหม่ด้านล่าง
        }
      // กันค้าง #2: ⭐ ค้างเกิน N แท่งไม่ trigger → วาง straddle ใหม่
      else if(SinglePendingTimedOut())
        {
         DeleteAllMyPendings(); ResetCycle();
         // ตกไปวาง straddle ใหม่ด้านล่าง
        }
      else
         return;  // ยังใกล้ + ยังไม่ timeout → รอ trigger ตามปกติ
     }
   else
     {
      g_singlePendBarTime = 0;   // ไม่มี pending → reset timer
     }

   // ============================================================
   // STATE C: flat สนิท (ไม่มี position, ไม่มี pending) → เริ่มรอบใหม่
   // ============================================================
   ResetCycle();

   if(g_cooldownUntil > 0 && TimeCurrent() < g_cooldownUntil) return;
   g_cooldownUntil = 0;

   if(InpUseTimeFilter && !IsWithinTradingTime()) return;
   if(!IsSpreadOK()) return;
   if(!IsTrendStrongEnough()) return;   // v10.42: ตลาด sideway (ADX ต่ำ) → ไม่วาง straddle ใหม่

   PlaceInitialStraddle();
  }

//+------------------------------------------------------------------+
//| ⭐ Risk Guard: ป้องกันล้างพอร์ตจากการวน Stop&Reverse ไม่หยุด       |
//| - Daily loss limit: ขาดทุนสะสมวันนี้เกิน % ของ balance ต้นวัน    |
//|   → ปิดทุกไม้ + ลบ pending + หยุดเทรดจนกว่าจะถึงวันใหม่ (server) |
//| - Max drawdown limit: equity ร่วงจาก peak เกิน %                |
//|   → ปิดทุกไม้ + ลบ pending + หยุด EA ถาวร (ต้องรีสตาร์ทเอง)       |
//| คืนค่า true = ถูกหยุดเทรด (OnTick ต้อง return ทันที)             |
//+------------------------------------------------------------------+
bool CheckRiskGuard()
  {
   if(!InpUseRiskGuard) return false;

   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   if(equity > g_peakEquity) g_peakEquity = equity;

   // --- รีเซ็ตวันใหม่ (server time เที่ยงคืน) ---
   MqlDateTime t; TimeToStruct(TimeCurrent(), t); t.hour=0; t.min=0; t.sec=0;
   datetime today = StructToTime(t);
   if(today != g_dayStart)
     {
      g_dayStart        = today;
      g_dayStartBalance = AccountInfoDouble(ACCOUNT_BALANCE);
     }

   if(g_haltedByGuard) return true;   // ชน max drawdown ไปแล้ว → หยุดถาวร ไม่ต้องเช็คอะไรอีก

   // --- Max drawdown จาก peak: หยุดถาวร ---
   if(InpMaxDrawdownPercent > 0 && g_peakEquity > 0)
     {
      double ddPct = (g_peakEquity - equity) / g_peakEquity * 100.0;
      if(ddPct >= InpMaxDrawdownPercent)
        {
         Print("⛔ Risk Guard: Equity drawdown ", DoubleToString(ddPct,2),
               "% จาก peak (limit ", DoubleToString(InpMaxDrawdownPercent,2), "%) → ปิดทุกไม้ + หยุด EA ถาวร");
         CloseAllAndFlatten();
         g_haltedByGuard = true;
         return true;
        }
     }

   // --- Daily loss limit: หยุดถึงวันใหม่ ---
   if(InpMaxDailyLossPercent > 0 && g_dayStartBalance > 0)
     {
      double dayLossPct = (g_dayStartBalance - equity) / g_dayStartBalance * 100.0;
      if(dayLossPct >= InpMaxDailyLossPercent)
        {
         Print("⛔ Risk Guard: ขาดทุนวันนี้ ", DoubleToString(dayLossPct,2),
               "% (limit ", DoubleToString(InpMaxDailyLossPercent,2), "%) → ปิดทุกไม้ + หยุดเทรดจนถึงวันใหม่");
         CloseAllAndFlatten();
         return true;
        }
     }

   return false;
  }

//+------------------------------------------------------------------+
//| ปิด position ทั้งหมด + ลบ pending ทั้งหมดของ EA นี้ (ฉุกเฉิน)     |
//+------------------------------------------------------------------+
void CloseAllAndFlatten()
  {
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber && posInfo.Symbol()==_Symbol)
            trade.PositionClose(posInfo.Ticket());
   DeleteAllMyPendings();
   ResetCycle();
  }

//+------------------------------------------------------------------+
//| reset state ของรอบ reverse (เริ่มรอบใหม่สะอาด)                  |
//+------------------------------------------------------------------+
void ResetCycle()
  {
   g_reverseCount = 0;
   g_lastDir = 0;
   g_revStopTicket = 0;
   g_singlePendBarTime = 0;   // reset timer timeout (ฝั่งเดียว)
  }

//+------------------------------------------------------------------+
//| นับจำนวน pending แต่ละฝั่ง (BUY STOP / SELL STOP)                |
//+------------------------------------------------------------------+
void CountPendingSides(int &nBuy, int &nSell)
  {
   nBuy=0; nSell=0;
   for(int i=OrdersTotal()-1;i>=0;i--)
      if(ordInfo.SelectByIndex(i))
         if(ordInfo.Magic()==InpMagicNumber && ordInfo.Symbol()==_Symbol)
           {
            ENUM_ORDER_TYPE ot=(ENUM_ORDER_TYPE)ordInfo.OrderType();
            if(ot==ORDER_TYPE_BUY_STOP)  nBuy++;
            else if(ot==ORDER_TYPE_SELL_STOP) nSell++;
           }
  }
//+------------------------------------------------------------------+
//| pending ฝั่งเดียวที่ค้าง ห่างจากราคาเกินไปไหม (กันค้าง)          |
//+------------------------------------------------------------------+
bool SinglePendingTooFar()
  {
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   if(ask<=0||bid<=0) return false;
   // ⭐ ใช้ระยะคงที่ที่สมเหตุสมผล แต่ไม่เล็กกว่า Gap (กันลบทันทีตอนกลายเป็น orphan)
   double maxAway = MathMax(InpMaxPendingDistance, InpReverseGap*2) * g_point;
   for(int i=OrdersTotal()-1;i>=0;i--)
      if(ordInfo.SelectByIndex(i))
         if(ordInfo.Magic()==InpMagicNumber && ordInfo.Symbol()==_Symbol)
           {
            double op = ordInfo.PriceOpen();
            double ref = (ordInfo.OrderType()==ORDER_TYPE_BUY_STOP)?ask:bid;
            if(MathAbs(op-ref) > maxAway)
              {
               Print("Single pending TooFar: ห่าง ", DoubleToString(MathAbs(op-ref)/g_point,0), " points (เกิน ", DoubleToString(maxAway/g_point,0), ") → วาง straddle ใหม่");
               return true;
              }
           }
   return false;
  }
//+------------------------------------------------------------------+
//| ⭐ pending ฝั่งเดียวค้างเกิน N แท่งไม่ trigger หรือยัง (timeout)  |
//| แก้ "ออเดอร์ไม่ต่อเนื่อง" — ไม่พึ่ง g_lastDir, ครอบคลุมทุกเคส   |
//+------------------------------------------------------------------+
bool SinglePendingTimedOut()
  {
   if(InpReverseTimeoutBars <= 0) return false;   // 0 = ปิดฟีเจอร์
   datetime curBar = iTime(_Symbol, PERIOD_M1, 0);
   if(g_singlePendBarTime == 0)                   // เพิ่งเริ่มเหลือฝั่งเดียว
     { g_singlePendBarTime = curBar; return false; }
   int barsPassed = iBarShift(_Symbol, PERIOD_M1, g_singlePendBarTime);
   if(barsPassed >= InpReverseTimeoutBars)
     {
      Print("Single pending timeout (", barsPassed, " แท่ง) → วาง straddle ใหม่");
      return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| เลื่อน straddle เริ่มต้นให้ตามราคา (re-center ทุกแท่งใหม่)        |
//| แก้ปัญหา: pending ค้างจุดเดิม ถ้าราคาวิ่งหนีไม่กลับมา EA ค้าง    |
//+------------------------------------------------------------------+
void RecenterStraddle()
  {
   // ทำเฉพาะเมื่อขึ้นแท่งใหม่ (ลด load + ลด requote)
   datetime curBar = iTime(_Symbol, PERIOD_M1, 0);
   if(curBar == g_lastBarTime) return;
   g_lastBarTime = curBar;

   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   if(ask<=0||bid<=0) return;

   ulong buyTkt  = FindMyReverseStop(ORDER_TYPE_BUY_STOP);
   ulong sellTkt = FindMyReverseStop(ORDER_TYPE_SELL_STOP);

   // ===== เคสผิดปกติ: เหลือ pending ฝั่งเดียว (อีกฝั่ง trigger/หาย) =====
   // หรือราคาวิ่งหนีไกลเกิน → ลบทั้งหมดแล้ววาง straddle ใหม่รอบราคาปัจจุบัน
   bool onlyOneSide = (buyTkt>0) != (sellTkt>0);   // XOR: มีฝั่งเดียว
   double maxAway = (InpStopDistance + InpRecenterTolerance*3) * g_point;

   bool tooFar = false;
   if(buyTkt>0 && ordInfo.Select(buyTkt))
      if(MathAbs(ordInfo.PriceOpen() - ask) > maxAway) tooFar = true;
   if(sellTkt>0 && ordInfo.Select(sellTkt))
      if(MathAbs(ordInfo.PriceOpen() - bid) > maxAway) tooFar = true;

   // ⭐ FIX: ถ้าเหลือฝั่งเดียว = อีกฝั่งเพิ่ง trigger เป็น position แล้ว
   // ห้ามลบ! ปล่อยให้ STATE A (ManagePositionAndReverse) จัดการรอบหน้า
   // ลบทิ้งตรงนี้ = บั๊กเดิมที่ทำให้ "ไม่เข้า order"
   if(onlyOneSide) return;

   // ถ้าครบ 2 ฝั่งแต่ราคาหนีไกลเกิน → วาง straddle ใหม่รอบราคาปัจจุบัน
   if(tooFar)
     {
      DeleteAllMyPendings();
      PlaceInitialStraddle();
      return;
     }

   // ===== เคสปกติ: ครบ 2 ฝั่ง แค่ขยับให้ตามราคา =====
   double wantBuy  = NormalizeDouble(ask + InpStopDistance*g_point, g_digits);
   double wantSell = NormalizeDouble(bid - InpStopDistance*g_point, g_digits);
   double tol = InpRecenterTolerance * g_point;

   if(buyTkt>0 && ordInfo.Select(buyTkt))
      if(MathAbs(ordInfo.PriceOpen()-wantBuy) > tol)
         trade.OrderModify(buyTkt, wantBuy, 0, 0, ORDER_TIME_GTC, 0);
   if(sellTkt>0 && ordInfo.Select(sellTkt))
      if(MathAbs(ordInfo.PriceOpen()-wantSell) > tol)
         trade.OrderModify(sellTkt, wantSell, 0, 0, ORDER_TIME_GTC, 0);
  }

//+------------------------------------------------------------------+
//| นับ pending ตาม order type ที่ระบุ (ของ EA เราเอง)                |
//+------------------------------------------------------------------+
int CountPendingOfType(ENUM_ORDER_TYPE ot)
  {
   int n=0;
   for(int i=OrdersTotal()-1;i>=0;i--)
      if(ordInfo.SelectByIndex(i))
         if(ordInfo.Magic()==InpMagicNumber && ordInfo.Symbol()==_Symbol)
            if((ENUM_ORDER_TYPE)ordInfo.OrderType()==ot) n++;
   return n;
  }

//+------------------------------------------------------------------+
//| วาง Buy Stop + Sell Stop เริ่มต้น                                |
//+------------------------------------------------------------------+
void PlaceInitialStraddle()
  {
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   if(ask<=0||bid<=0) return;
   long stopsLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   double minDist = (stopsLevel+2) * g_point;
   double useDist = MathMax(InpStopDistance*g_point, minDist);   // ⭐ กันโบรกปฏิเสธถ้า StopDistance ตั้งแคบเกิน
   double bP=NormalizeDouble(ask+useDist,g_digits);
   double sP=NormalizeDouble(bid-useDist,g_digits);
   // ⭐ TP สำหรับ pending (0=ปิด): BuyStop → TP เหนือ, SellStop → TP ใต้
   double tpBuy  = (InpTakeProfit>0) ? NormalizeDouble(bP + InpTakeProfit*g_point, g_digits) : 0;
   double tpSell = (InpTakeProfit>0) ? NormalizeDouble(sP - InpTakeProfit*g_point, g_digits) : 0;
   double lot=CalculateLot(InpInitialSL);
   if(lot<=0) return;
   datetime exp=0; ENUM_ORDER_TYPE_TIME tt=ORDER_TIME_GTC;
   if(InpPendingExpiryMin>0){exp=TimeCurrent()+InpPendingExpiryMin*60;tt=ORDER_TIME_SPECIFIED;}

   int nBuy=0, nSell=0;
   CountPendingSides(nBuy, nSell);

   // ⭐ วางเฉพาะฝั่งที่ยังไม่มี (กันวางซ้ำ + เติมฝั่งที่หายไปจากการ retry)
   bool okBuy=true, okSell=true;
   if(nBuy==0)
     {
      okBuy = trade.BuyStop(lot,bP,_Symbol,0,tpBuy,tt,exp,InpComment);
      if(!okBuy) Print("⚠️ BuyStop วางไม่สำเร็จ: ", trade.ResultRetcodeDescription());
     }
   if(nSell==0)
     {
      okSell = trade.SellStop(lot,sP,_Symbol,0,tpSell,tt,exp,InpComment);
      if(!okSell) Print("⚠️ SellStop วางไม่สำเร็จ: ", trade.ResultRetcodeDescription());
     }
   if(!okBuy || !okSell)
      Print("Straddle ไม่ครบ — จะลองใหม่ tick ถัดไป (nBuy=", nBuy, " nSell=", nSell, ")");

   g_reverseCount = 0;
   g_lastBarTime = iTime(_Symbol, PERIOD_M1, 0);  // เริ่มนับแท่งสำหรับ re-center
  }

//+------------------------------------------------------------------+
//| ⭐ Progressive Trailing (v10.4): คำนวณ SL แนะนำตามโหมดที่เลือก     |
//| ปิด (default) → 2 ขั้นเดิม: Breakeven คงที่ จนกว่าจะถึง           |
//|   TrailingStart ค่อยเปลี่ยนเป็น Trailing (มี "หลุมว่าง" ระหว่างกลาง)|
//| เปิด → ไหลต่อเนื่อง: หลัง Breakeven, SL ขยับตามกำไรทุกจุด          |
//|   ด้วยอัตรา InpTrailRatio จนถึง TrailingStart แล้วสลับเป็น        |
//|   Trailing ปกติ (ไม่มีหลุมว่างอีก)                               |
//| คืนค่า 0 = ยังไม่ถึงเกณฑ์ใดเลย (ไม่ต้องขยับ SL)                  |
//+------------------------------------------------------------------+
double ComputeTrailCandidate(bool isBuy, double open, double bid, double ask, double profitPts)
  {
   if(InpTrailingStart>0 && profitPts>=InpTrailingStart)
     {
      // เกิน TrailingStart แล้ว → Trailing แบบเดิมเสมอ (ทั้ง 2 โหมด)
      return isBuy ? NormalizeDouble(bid-InpTrailingDistance*g_point,g_digits)
                   : NormalizeDouble(ask+InpTrailingDistance*g_point,g_digits);
     }
   if(InpBreakevenStart>0 && profitPts>=InpBreakevenStart)
     {
      if(InpUseProgressiveTrail)
        {
         // ⭐ โซน progressive: ไหลต่อเนื่องตามกำไรส่วนเกิน ไม่ค้างนิ่ง
         double excess = profitPts - InpBreakevenStart;
         double extra  = excess*InpTrailRatio*g_point;
         return isBuy ? NormalizeDouble(open+InpBreakevenLock*g_point+extra,g_digits)
                      : NormalizeDouble(open-InpBreakevenLock*g_point-extra,g_digits);
        }
      // ของเดิม: ล็อกคงที่ ไม่ขยับจนกว่าจะถึง TrailingStart
      return isBuy ? NormalizeDouble(open+InpBreakevenLock*g_point,g_digits)
                   : NormalizeDouble(open-InpBreakevenLock*g_point,g_digits);
     }
   return 0;   // ยังไม่ถึง BreakevenStart เลย → ไม่มีค่าแนะนำ
  }

//+------------------------------------------------------------------+
//| จัดการ position + เลื่อน Reverse Stop เกาะติด SL                 |
//+------------------------------------------------------------------+
void ManagePositionAndReverse()
  {
   // ความปลอดภัยบัญชี Hedging: ถ้ามีมากกว่า 1 position
   // (reverse เปิดสวนโดยไม่ปิดเก่าอัตโนมัติ) ปิดไม้เก่าให้เหลือไม้ล่าสุด
   if(CountMyPositions() > 1) CloseOldestKeepNewest();

   if(!SelectMyPosition()) return;
   OnTradeReverseCheck();  // ตรวจว่าเพิ่ง reverse หรือไม่ (นับ count)
   if(!SelectMyPosition()) return;
   double open=posInfo.PriceOpen();
   double sl=posInfo.StopLoss();
   double tp=posInfo.TakeProfit();
   ulong  tkt=posInfo.Ticket();
   long   ptype=posInfo.PositionType();
   double bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK);

   g_lastDir = (ptype==POSITION_TYPE_BUY)?1:-1;
   g_singlePendBarTime = 0;  // มี position อยู่ → reset timer ฝั่งเดียว

   // ===== จัดการ pending ฝั่งตรงข้ามที่ค้างจาก straddle เริ่มต้น =====
   // ⭐ สำคัญ: ไม่ลบทิ้ง! แต่ "เก็บไว้ใช้เป็น reverse stop"
   // BUY position → เก็บ SELL STOP (ฝั่งล่าง) เป็น reverse, ลบ BUY STOP ส่วนเกิน
   // SELL position → เก็บ BUY STOP (ฝั่งบน) เป็น reverse, ลบ SELL STOP ส่วนเกิน
   ConvertStrayToReverse(ptype);

   double profitPts = (ptype==POSITION_TYPE_BUY) ? (bid-open)/g_point : (open-ask)/g_point;

   // ===== 1) คำนวณตำแหน่ง SL ใหม่ (initial / breakeven / trailing) =====
   double newSL = sl;
   double slForReverse = sl;   // ตำแหน่ง SL ที่จะใช้วาง reverse stop (แม้ modify ยังไม่ติด)
   if(ptype==POSITION_TYPE_BUY)
     {
      // SL เริ่มต้น ถ้ายังไม่มี
      if(sl==0) newSL = NormalizeDouble(open - InpInitialSL*g_point, g_digits);
      double cand = ComputeTrailCandidate(true, open, bid, ask, profitPts);
      if(cand>0) newSL = MathMax(newSL, cand);
      if(newSL>sl+g_point*0.5 && newSL<bid) { trade.PositionModify(tkt,newSL,tp); sl=newSL; }
      slForReverse = newSL;   // ใช้ค่าเป้าหมายเสมอ (ไม่รอ modify สำเร็จ)
     }
   else // SELL
     {
      if(sl==0) newSL = NormalizeDouble(open + InpInitialSL*g_point, g_digits);
      double cand = ComputeTrailCandidate(false, open, bid, ask, profitPts);
      if(cand>0) newSL = (sl==0) ? cand : MathMin(newSL, cand);
      if(newSL>0 && (sl==0||newSL<sl-g_point*0.5) && newSL>ask) { trade.PositionModify(tkt,newSL,tp); sl=newSL; }
      slForReverse = newSL;   // ใช้ค่าเป้าหมายเสมอ
     }

   // ===== 2) วาง/เลื่อน Reverse Stop ให้เกาะติด SL (ห่าง gap) =====
   // ⭐ ใช้ slForReverse (ค่าเป้าหมาย) เพื่อให้ reverse stop วางได้เสมอ
   //    แม้ PositionModify ยังไม่ติด — กันเคส "SELL ปิดแต่ไม่มี BUY ให้ reverse"
   if(InpUseReverse && g_reverseCount < InpMaxReverses && slForReverse>0)
     {
      UpdateReverseStop(ptype, slForReverse);
     }
  }

//+------------------------------------------------------------------+
//| วาง/เลื่อน Reverse Stop เกาะติด SL ห่าง InpReverseGap            |
//| BUY position  → Reverse = SELL STOP ใต้ SL (เลยลงไป gap)         |
//| SELL position → Reverse = BUY STOP เหนือ SL (เลยขึ้นไป gap)      |
//+------------------------------------------------------------------+
void UpdateReverseStop(long ptype, double slPrice)
  {
   double lot = CalculateLot(InpInitialSL);
   if(lot<=0) return;

   double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK), bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
   long stopsLevel = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   double minDist = (stopsLevel+2) * g_point;   // ระยะขั้นต่ำที่โบรกยอมให้วาง pending

   double revPrice;
   ENUM_ORDER_TYPE revType;
   if(ptype==POSITION_TYPE_BUY)
     {
      // reverse เป็น SELL STOP ใต้ SL ลงไปอีก gap
      revPrice = NormalizeDouble(slPrice - InpReverseGap*g_point, g_digits);
      // SELL STOP ต้องต่ำกว่า Bid อย่างน้อย minDist
      if(revPrice > bid - minDist) revPrice = NormalizeDouble(bid - minDist, g_digits);
      revType  = ORDER_TYPE_SELL_STOP;
     }
   else
     {
      // reverse เป็น BUY STOP เหนือ SL ขึ้นไปอีก gap
      revPrice = NormalizeDouble(slPrice + InpReverseGap*g_point, g_digits);
      // BUY STOP ต้องสูงกว่า Ask อย่างน้อย minDist
      if(revPrice < ask + minDist) revPrice = NormalizeDouble(ask + minDist, g_digits);
      revType  = ORDER_TYPE_BUY_STOP;
     }

   // หา reverse stop เดิม (ถ้ามี) แล้ว modify ราคา ไม่งั้นวางใหม่
   ulong existing = FindMyReverseStop(revType);
   if(existing>0)
     {
      if(ordInfo.Select(existing))
        {
         double curPrice = ordInfo.PriceOpen();
         if(MathAbs(curPrice-revPrice) > g_point*0.5)
            trade.OrderModify(existing, revPrice, 0, 0, ORDER_TIME_GTC, 0);
        }
     }
   else
     {
      // ไม่มี reverse stop ฝั่งที่ต้องการ → วางใหม่
      // (ส่วน same-side ถูกลบโดย ConvertStrayToReverse แล้ว ไม่ต้อง DeleteAll)
      // ⭐ TP สำหรับ reverse (0=ปิด): SELL STOP → TP ใต้, BUY STOP → TP เหนือ
      if(revType==ORDER_TYPE_SELL_STOP)
        {
         double tpRev = (InpTakeProfit>0)?NormalizeDouble(revPrice - InpTakeProfit*g_point,g_digits):0;
         trade.SellStop(lot, revPrice, _Symbol, 0, tpRev, ORDER_TIME_GTC, 0, InpComment+"_REV");
        }
      else
        {
         double tpRev = (InpTakeProfit>0)?NormalizeDouble(revPrice + InpTakeProfit*g_point,g_digits):0;
         trade.BuyStop(lot, revPrice, _Symbol, 0, tpRev, ORDER_TIME_GTC, 0, InpComment+"_REV");
        }
     }
  }

//+------------------------------------------------------------------+
//| ตรวจจับการ reverse: ถ้า position เปลี่ยนทิศ = เพิ่ง reverse      |
//| เรียกตอน position ใหม่ trigger จาก reverse stop                  |
//+------------------------------------------------------------------+
void OnTradeReverseCheck()
  {
   // ใช้ใน OnTick: ถ้ามี position ทิศตรงข้าม g_lastDir = เพิ่ง reverse
   if(!SelectMyPosition()) return;
   int curDir = (posInfo.PositionType()==POSITION_TYPE_BUY)?1:-1;
   if(g_lastDir!=0 && curDir!=g_lastDir)
     {
      g_reverseCount++;
      g_lastDir = curDir;
      g_revStopTicket = 0;
      if(g_reverseCount>=InpMaxReverses && InpReverseCooldownM>0)
         g_cooldownUntil = TimeCurrent()+InpReverseCooldownM*60;
     }
  }

//=================== PANEL ==========================================
void PanelCreate()
  {
   int x=InpPanelX, y=InpPanelY;
   Rect(PFX+"BG", x, y, PW, 300, CLR_BG, CLR_BORDER);
   Rect(PFX+"ACC", x, y, PW, 2, CLR_CYAN, CLR_CYAN);
   Rect(PFX+"HDR", x, y+2, PW, 46, CLR_HDR, CLR_BG);
   Label(PFX+"T1", x+12, y+9, "◈  STRADDLE SCALPER", "Consolas", 10, CLR_CYAN);
   Label(PFX+"T2", x+PW-95, y+9, "v10.5·TSR", "Consolas", 9, CLR_AMBER);
   Label(PFX+"T3", x+12, y+28, _Symbol+" · M1 · TSR Continuous", "Consolas", 8, CLR_DIM);
   Rect(PFX+"D1", x, y+48, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"STBG", x, y+49, PW, 26, CLR_SURFACE, CLR_BG);
   Rect(PFX+"DOT", x+12, y+58, 8, 8, CLR_GREEN, CLR_GREEN);
   Label(PFX+"STAT", x+26, y+56, "READY", "Consolas", 9, CLR_GREEN);
   Label(PFX+"TIME", x+150, y+56, "ไทย: --", "Consolas", 8, CLR_DIM);
   Rect(PFX+"D2", x, y+76, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"ACB", x, y+77, PW, 70, CLR_BG, CLR_BG);
   int ay=y+82;
   Label(PFX+"BL", x+12, ay, "BALANCE", "Consolas", 8, CLR_DIM);
   Label(PFX+"BV", x+90, ay, "$0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"EQ", x+12, ay+22, "EQUITY", "Consolas", 8, CLR_DIM);
   Label(PFX+"EV", x+90, ay+22, "$0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"FL", x+190, ay+22, "+$0", "Consolas", 8, CLR_GREEN);
   Label(PFX+"TD", x+12, ay+44, "TODAY", "Consolas", 8, CLR_DIM);
   Label(PFX+"TV", x+90, ay+44, "+$0", "Consolas", 9, CLR_GREEN);
   Rect(PFX+"D3", x, y+147, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"PRB", x, y+148, PW, 46, CLR_SURFACE, CLR_BG);
   int py=y+153;
   Label(PFX+"DIR", x+12, py, "DIR", "Consolas", 8, CLR_DIM);
   Label(PFX+"DIRV", x+50, py, "-", "Consolas", 9, CLR_CYAN);
   Label(PFX+"RV", x+110, py, "REVERSE", "Consolas", 8, CLR_DIM);
   Label(PFX+"RVV", x+185, py, "0", "Consolas", 9, CLR_AMBER);
   Label(PFX+"RVMAX", x+205, py, "/0", "Consolas", 9, CLR_DIM);
   Label(PFX+"LT", x+12, py+22, "LOT", "Consolas", 8, CLR_DIM);
   Label(PFX+"LTV", x+50, py+22, "0", "Consolas", 9, CLR_TEXT);
   Label(PFX+"GP", x+110, py+22, "GAP", "Consolas", 8, CLR_DIM);
   Label(PFX+"GPV", x+150, py+22, "0", "Consolas", 9, CLR_RED);
   Rect(PFX+"D4", x, y+195, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"SSB", x, y+196, PW, 46, CLR_BG, CLR_BG);
   int sy=y+201;
   Label(PFX+"WN", x+12, sy, "WIN", "Consolas", 8, CLR_DIM);
   Label(PFX+"WNV", x+42, sy, "0", "Consolas", 9, CLR_GREEN);
   Label(PFX+"LS", x+78, sy, "LOSS", "Consolas", 8, CLR_DIM);
   Label(PFX+"LSV", x+112, sy, "0", "Consolas", 9, CLR_RED);
   Label(PFX+"WR", x+148, sy, "WR", "Consolas", 8, CLR_DIM);
   Label(PFX+"WRV", x+172, sy, "0%", "Consolas", 9, CLR_CYAN);
   Label(PFX+"PF", x+12, sy+22, "PF", "Consolas", 8, CLR_DIM);
   Label(PFX+"PFV", x+38, sy+22, "0", "Consolas", 9, CLR_AMBER);
   Label(PFX+"SP", x+138, sy+22, "SPREAD", "Consolas", 8, CLR_DIM);
   Label(PFX+"SPV", x+205, sy+22, "0", "Consolas", 9, CLR_TEXT);
   Rect(PFX+"D5", x, y+242, PW, 1, CLR_BORDER, CLR_BORDER);
   Rect(PFX+"BEB", x, y+243, PW, 30, CLR_SURFACE, CLR_BG);
   int by=y+253;
   Label(PFX+"NEEDL", x+12, by, "B/E WR", "Consolas", 8, CLR_DIM);
   Label(PFX+"NEEDV", x+70, by, "--", "Consolas", 9, CLR_TEXT);
   Label(PFX+"BUFL", x+140, by, "BUFFER", "Consolas", 8, CLR_DIM);
   Label(PFX+"BUFV", x+205, by, "--", "Consolas", 9, CLR_DIM);
   Rect(PFX+"BOT", x, y+274, PW, 18, CLR_HDR, CLR_BG);
   Label(PFX+"BX", x+12, y+279, "MAGIC: "+IntegerToString(InpMagicNumber), "Consolas", 7, CLR_MUTED);
   ChartRedraw(0);
  }

void PanelUpdate()
  {
   double bal=AccountInfoDouble(ACCOUNT_BALANCE),eq=AccountInfoDouble(ACCOUNT_EQUITY),fl=eq-bal;
   long spread=SymbolInfoInteger(_Symbol,SYMBOL_SPREAD);
   double lot=CalculateLot(InpInitialSL);
   MqlDateTime t; TimeToStruct(TimeCurrent(),t); t.hour=0;t.min=0;t.sec=0;
   datetime today=StructToTime(t);
   HistorySelect(today,TimeCurrent());
   double dP=0,dL=0; int w=0,l=0;
   for(int i=0;i<HistoryDealsTotal();i++)
     {
      ulong tk=HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(tk,DEAL_MAGIC)!=InpMagicNumber) continue;
      if(HistoryDealGetInteger(tk,DEAL_ENTRY)!=DEAL_ENTRY_OUT) continue;
      double p=HistoryDealGetDouble(tk,DEAL_PROFIT)+HistoryDealGetDouble(tk,DEAL_SWAP)+HistoryDealGetDouble(tk,DEAL_COMMISSION);
      if(p>=0){dP+=p;w++;}else{dL+=MathAbs(p);l++;}
     }
   double net=dP-dL,pf=(dL>0?dP/dL:(dP>0?999:0)),wr=(w+l>0?100.0*w/(w+l):0);

   // ⭐ Breakeven WR Display — คำนวณ WR ที่ "เท่าทุน" จากสัดส่วนไม้ชนะ/แพ้เฉลี่ยจริงวันนี้
   // ไม่เปลี่ยนพฤติกรรมเทรดใดๆ แค่แสดงผล ใช้เฝ้าดูความเปราะของระบบ
   double wrBE = 0; bool haveBE = false; double buffer = 0;
   if(w>0 && l>0 && dP>0 && dL>0)
     {
      double avgWin = dP/w, avgLoss = dL/l;
      double ratioWL = avgWin/avgLoss;           // เฉลี่ยชนะ : เฉลี่ยแพ้
      if(ratioWL>0) { wrBE = 100.0/(1.0+ratioWL); haveBE = true; buffer = wr - wrBE; }
     }
   string stat="READY"; color dc=CLR_GREEN,sc=CLR_GREEN;
   bool timeOk = !InpUseTimeFilter || IsWithinTradingTime();
   if(CountMyPositions()>0){stat="IN TRADE";dc=CLR_CYAN;sc=CLR_CYAN;}
   else if(CountMyPendings()>0){stat="WAIT/REVERSE";dc=CLR_AMBER;sc=CLR_AMBER;}
   else if(g_cooldownUntil>TimeCurrent()){stat="COOLDOWN";dc=CLR_RED;sc=CLR_RED;}
   else if(!timeOk){stat="OUT OF TIME";dc=CLR_RED;sc=CLR_RED;}
   ObjColor(PFX+"DOT",dc); ObjColor(PFX+"STAT",sc); ObjText(PFX+"STAT",stat);
   datetime thaiTime=TimeCurrent()-InpServerGMTOffset*3600+7*3600;
   MqlDateTime tn; TimeToStruct(thaiTime,tn);
   ObjText(PFX+"TIME",StringFormat("ไทย: %02d:%02d %s",tn.hour,tn.min,timeOk?"✓":"✗"));
   ObjColor(PFX+"TIME",timeOk?CLR_DIM:CLR_RED);
   ObjText(PFX+"BV","$"+DoubleToString(bal,2));
   ObjText(PFX+"EV","$"+DoubleToString(eq,2));
   ObjText(PFX+"FL",(fl>=0?"+":"")+DoubleToString(fl,2)); ObjColor(PFX+"FL",fl>=0?CLR_GREEN:CLR_RED);
   ObjText(PFX+"TV",(net>=0?"+$":"-$")+DoubleToString(MathAbs(net),2)); ObjColor(PFX+"TV",net>=0?CLR_GREEN:CLR_RED);
   string dirTxt = g_lastDir==1?"BUY":(g_lastDir==-1?"SELL":"-");
   ObjText(PFX+"DIRV",dirTxt);
   ObjColor(PFX+"DIRV", g_lastDir==1?CLR_CYAN:(g_lastDir==-1?CLR_RED:CLR_DIM));
   ObjText(PFX+"RVV",(string)g_reverseCount);
   ObjText(PFX+"RVMAX","/"+(string)InpMaxReverses);
   ObjText(PFX+"LTV",DoubleToString(lot,2));
   ObjText(PFX+"GPV",(string)InpReverseGap);
   ObjText(PFX+"WNV",(string)w);
   ObjText(PFX+"LSV",(string)l);
   ObjText(PFX+"WRV",DoubleToString(wr,1)+"%");
   ObjText(PFX+"PFV",pf>=999?"inf":DoubleToString(pf,2));
   // ⭐ Breakeven WR Display
   if(haveBE)
     {
      ObjText(PFX+"NEEDV",DoubleToString(wrBE,1)+"%");
      ObjText(PFX+"BUFV",(buffer>=0?"+":"")+DoubleToString(buffer,1));
      color bufColor = (buffer>=5)?CLR_GREEN:(buffer>0?CLR_AMBER:CLR_RED);
      ObjColor(PFX+"BUFV",bufColor);
      ObjColor(PFX+"NEEDV",CLR_TEXT);
     }
   else
     {
      ObjText(PFX+"NEEDV","--");
      ObjText(PFX+"BUFV","--");
      ObjColor(PFX+"BUFV",CLR_DIM);
     }
   ObjText(PFX+"SPV",(string)spread);
   ObjColor(PFX+"SPV",(InpMaxSpread<=0||spread<=InpMaxSpread)?CLR_GREEN:CLR_RED);
   ChartRedraw(0);
  }

void PanelDelete(){ ObjectsDeleteAll(0,PFX); ChartRedraw(0); }
void Rect(string n,int x,int y,int w,int h,color bg,color bd)
  {
   if(ObjectFind(0,n)<0) ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);
   ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);
   ObjectSetInteger(0,n,OBJPROP_XSIZE,w); ObjectSetInteger(0,n,OBJPROP_YSIZE,h);
   ObjectSetInteger(0,n,OBJPROP_BGCOLOR,bg); ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,bd);
   ObjectSetInteger(0,n,OBJPROP_BORDER_TYPE,BORDER_FLAT); ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);
   ObjectSetInteger(0,n,OBJPROP_BACK,false); ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,n,OBJPROP_HIDDEN,true);
  }
void Label(string n,int x,int y,string txt,string f,int s,color c)
  {
   if(ObjectFind(0,n)<0) ObjectCreate(0,n,OBJ_LABEL,0,0,0);
   ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x); ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);
   ObjectSetString(0,n,OBJPROP_TEXT,txt); ObjectSetString(0,n,OBJPROP_FONT,f);
   ObjectSetInteger(0,n,OBJPROP_FONTSIZE,s); ObjectSetInteger(0,n,OBJPROP_COLOR,c);
   ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);
   ObjectSetInteger(0,n,OBJPROP_BACK,false); ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false); ObjectSetInteger(0,n,OBJPROP_HIDDEN,true);
  }
void ObjText(string n,string t){ ObjectSetString(0,n,OBJPROP_TEXT,t); }
void ObjColor(string n,color c){ ObjectSetInteger(0,n,OBJPROP_COLOR,c); }

void WriteDashboardJSON()
  {
   double bal=AccountInfoDouble(ACCOUNT_BALANCE),eq=AccountInfoDouble(ACCOUNT_EQUITY);
   long sp=SymbolInfoInteger(_Symbol,SYMBOL_SPREAD);
   bool timeOk = !InpUseTimeFilter || IsWithinTradingTime();
   string as=!timeOk?"low":"active";
   MqlDateTime t; TimeToStruct(TimeCurrent(),t); t.hour=0;t.min=0;t.sec=0;
   datetime today=StructToTime(t);
   HistorySelect(today,TimeCurrent());
   double dP=0,dL=0,gW=0,gL=0; int w=0,l=0; string dj=""; int sh=0;
   for(int i=HistoryDealsTotal()-1;i>=0;i--)
     {
      ulong tk=HistoryDealGetTicket(i);
      if(HistoryDealGetInteger(tk,DEAL_MAGIC)!=InpMagicNumber) continue;
      if(HistoryDealGetInteger(tk,DEAL_ENTRY)!=DEAL_ENTRY_OUT) continue;
      double p=HistoryDealGetDouble(tk,DEAL_PROFIT)+HistoryDealGetDouble(tk,DEAL_SWAP)+HistoryDealGetDouble(tk,DEAL_COMMISSION);
      if(p>=0){dP+=p;gW+=p;w++;}else{dL+=MathAbs(p);gL+=MathAbs(p);l++;}
      if(sh<12){
        double vol=HistoryDealGetDouble(tk,DEAL_VOLUME); datetime dt=(datetime)HistoryDealGetInteger(tk,DEAL_TIME);
        long dt2=HistoryDealGetInteger(tk,DEAL_TYPE);
        if(sh>0) dj+=",";
        dj+=StringFormat("{\"time\":\"%s\",\"type\":\"%s\",\"lots\":%.2f,\"profit\":%.2f}",TimeToString(dt,TIME_MINUTES),dt2==DEAL_TYPE_BUY?"SELL":"BUY",vol,p); sh++;}
     }
   double pf=(gL>0?gW/gL:(gW>0?999:0)),wr=(w+l>0?100.0*w/(w+l):0);
   // ⭐ Breakeven WR (เหมือนใน Panel) สำหรับ export ดูประวัติย้อนหลังได้
   double wrBE_j=0; bool haveBE_j=false;
   if(w>0 && l>0 && gW>0 && gL>0)
     {
      double ratio_j = (gW/w)/(gL/l);
      if(ratio_j>0){ wrBE_j = 100.0/(1.0+ratio_j); haveBE_j=true; }
     }
   string pj=""; int np=0;
   for(int i=0;i<PositionsTotal();i++){
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic()!=InpMagicNumber||posInfo.Symbol()!=_Symbol) continue;
      if(np>0) pj+=",";
      pj+=StringFormat("{\"ticket\":%llu,\"type\":\"%s\",\"lots\":%.2f,\"open\":%.2f,\"current\":%.2f,\"profit\":%.2f}",
         posInfo.Ticket(),posInfo.PositionType()==POSITION_TYPE_BUY?"BUY":"SELL",posInfo.Volume(),posInfo.PriceOpen(),posInfo.PriceCurrent(),posInfo.Profit()); np++;}
   string json="{";
   json+=StringFormat("\"updated\":\"%s\",\"symbol\":\"%s\",",TimeToString(TimeCurrent(),TIME_DATE|TIME_SECONDS),_Symbol);
   json+=StringFormat("\"balance\":%.2f,\"equity\":%.2f,\"floating\":%.2f,",bal,eq,eq-bal);
   json+=StringFormat("\"dailyProfit\":%.2f,\"dailyLoss\":%.2f,",dP,dL);
   json+=StringFormat("\"wins\":%d,\"losses\":%d,\"winrate\":%.1f,\"profitFactor\":%.2f,",w,l,wr,pf);
   json+=StringFormat("\"breakevenWR\":%s,\"wrBuffer\":%s,",
         haveBE_j?DoubleToString(wrBE_j,1):"null",
         haveBE_j?DoubleToString(wr-wrBE_j,1):"null");
   json+=StringFormat("\"atr\":0.0,\"atrState\":\"%s\",\"atrMin\":0,\"atrMax\":0,",as);
   json+=StringFormat("\"straddleDist\":%d,\"slDist\":%d,\"tpDist\":0,",InpStopDistance,InpInitialSL);
   json+=StringFormat("\"spread\":%d,\"lot\":%.2f,\"pendings\":%d,\"reverses\":%d,",sp,CalculateLot(InpInitialSL),CountMyPendings(),g_reverseCount);
   json+="\"positions\":["+pj+"],\"deals\":["+dj+"]}";
   int fh=FileOpen(InpDashboardFile,FILE_WRITE|FILE_TXT|FILE_ANSI);
   if(fh!=INVALID_HANDLE){FileWriteString(fh,json);FileClose(fh);}
  }

double CalculateLot(int slP)
  {
   double lot;
   if(!InpUseAutoLot) lot=InpMinLot;
   else if(InpLotByBalanceStep) lot=MathFloor(AccountInfoDouble(ACCOUNT_BALANCE)/InpBalancePerLot)*0.01;
   else{
      double bal=AccountInfoDouble(ACCOUNT_BALANCE),risk=bal*InpRiskPercent/100.0;
      double tv=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE),ts=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE);
      if(tv<=0||ts<=0) return InpMinLot;
      double lpl=(slP*g_point/ts)*tv; if(lpl<=0) return InpMinLot;
      lot=risk/lpl;}
   double vMin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),vMax=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),vS=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lot=MathMax(lot,MathMax(InpMinLot,vMin)); lot=MathMin(lot,MathMin(InpMaxLot,vMax));
   if(vS>0) lot=MathFloor(lot/vS)*vS;
   return NormalizeDouble(lot,2);
  }

bool SelectMyPosition()
  {
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber&&posInfo.Symbol()==_Symbol) return true;
   return false;
  }
//+------------------------------------------------------------------+
//| บัญชี Hedging: ปิดไม้เก่า เก็บไม้ล่าสุด (ทิศ reverse ใหม่)        |
//+------------------------------------------------------------------+
void CloseOldestKeepNewest()
  {
   ulong newestTkt=0; datetime newestTime=0;
   // หาไม้ล่าสุด (เวลาเปิดมากสุด)
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber&&posInfo.Symbol()==_Symbol)
           {
            datetime tOpen=(datetime)posInfo.Time();
            if(tOpen>=newestTime){ newestTime=tOpen; newestTkt=posInfo.Ticket(); }
           }
   // ปิดทุกไม้ที่ไม่ใช่ล่าสุด
   for(int i=PositionsTotal()-1;i>=0;i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Magic()==InpMagicNumber&&posInfo.Symbol()==_Symbol)
            if(posInfo.Ticket()!=newestTkt)
               trade.PositionClose(posInfo.Ticket());
  }
ulong FindMyReverseStop(ENUM_ORDER_TYPE wantType)
  {
   for(int i=OrdersTotal()-1;i>=0;i--)
      if(ordInfo.SelectByIndex(i))
         if(ordInfo.Magic()==InpMagicNumber && ordInfo.Symbol()==_Symbol)
            if(ordInfo.OrderType()==wantType) return ordInfo.Ticket();
   return 0;
  }
//+------------------------------------------------------------------+
//| แปลง pending ฝั่งตรงข้ามที่ค้าง → reverse stop (ไม่ลบทิ้ง!)       |
//| BUY position  → เก็บ SELL STOP (ใต้) เป็น reverse                |
//| SELL position → เก็บ BUY STOP (เหนือ) เป็น reverse               |
//| ลบเฉพาะ pending ฝั่งเดียวกับ position (straddle ที่ trigger แล้ว) |
//+------------------------------------------------------------------+
void ConvertStrayToReverse(long ptype)
  {
   ENUM_ORDER_TYPE dropType;
   if(ptype==POSITION_TYPE_BUY)
      dropType=ORDER_TYPE_BUY_STOP;   // BUY pos → ลบ BUY STOP ส่วนเกิน เก็บ SELL STOP
   else
      dropType=ORDER_TYPE_SELL_STOP;  // SELL pos → ลบ SELL STOP ส่วนเกิน เก็บ BUY STOP

   for(int i=OrdersTotal()-1;i>=0;i--)
      if(ordInfo.SelectByIndex(i))
         if(ordInfo.Magic()==InpMagicNumber && ordInfo.Symbol()==_Symbol)
           {
            ENUM_ORDER_TYPE ot=(ENUM_ORDER_TYPE)ordInfo.OrderType();
            // ลบ stop ฝั่งเดียวกับ position ที่เพิ่ง trigger (ใช้ไปแล้ว)
            if(ot==dropType) trade.OrderDelete(ordInfo.Ticket());
           }
   // ฝั่ง reverse ที่เหลือ (STOP ตรงข้าม): UpdateReverseStop จะ modify ให้เกาะ SL + tag _REV เอง
  }
int CountMyPositions(){int n=0;for(int i=PositionsTotal()-1;i>=0;i--) if(posInfo.SelectByIndex(i)) if(posInfo.Magic()==InpMagicNumber&&posInfo.Symbol()==_Symbol) n++;return n;}
int CountMyPendings(){int n=0;for(int i=OrdersTotal()-1;i>=0;i--) if(ordInfo.SelectByIndex(i)) if(ordInfo.Magic()==InpMagicNumber&&ordInfo.Symbol()==_Symbol) n++;return n;}
void DeleteAllMyPendings(){for(int i=OrdersTotal()-1;i>=0;i--) if(ordInfo.SelectByIndex(i)) if(ordInfo.Magic()==InpMagicNumber&&ordInfo.Symbol()==_Symbol) trade.OrderDelete(ordInfo.Ticket());}

bool IsWithinTradingTime()
  {
   datetime thaiNow=TimeCurrent()-InpServerGMTOffset*3600+7*3600;
   MqlDateTime t; TimeToStruct(thaiNow,t);
   int cur=t.hour*60+t.min, s, e;
   switch(InpSession)
     {
      case SESS_ASIAN:     s=6*60;  e=14*60; break;
      case SESS_LONDON_NY: s=14*60; e=4*60;  break;
      case SESS_OVERLAP:   s=19*60; e=23*60; break;
      case SESS_ALL:       return true;
      default:             s=InpStartHour*60+InpStartMinute; e=InpEndHour*60+InpEndMinute; break;
     }
   return(s<=e ? cur>=s&&cur<=e : cur>=s||cur<=e);
  }
bool IsSpreadOK(){if(InpMaxSpread<=0) return true; return SymbolInfoInteger(_Symbol,SYMBOL_SPREAD)<=InpMaxSpread;}
